
---
title: "Correlación canónica"
---


El análisis de correlación canónica busca identificar y cuantificar las asociaciones lineales entre dos grupos de variables, es un complemento útil para un análisis de regresión multivariante, este análisis se enfoca en la correlación entre combinaciones lineales pertenecientes a los grupos de variables, por ejemplo:

- un conjunto de variables de aptitud y un conjunto de variables de rendimiento
- un conjunto de variables de personalidad y un conjunto de medidas de habilidad
- un conjunto de índices de precios y un conjunto de índices de producción
- un conjunto de comportamientos estudiantiles y un conjunto de comportamientos docentes 


La idea es determinar el par de combinaciones lineales que tienen la correlación más alta, luego el segundo par cuya correlación es menor o igual a la primera, y  así sucesivamente.  A estos pares de combinaciones lineales se los denomina variables canónicas, por consiguiente sus correlaciones son llamadas correlaciones canónicas, las mismas que miden la fuerza de asociación  entre los dos grupos de variables.

El primer grupo de variables está representado por el vector aleatorio p variado $\bf X_1$, el segundo grupo, de q variables es representado por $\bf X_2$, donde el primer conjunto de variables tiene menos componentes que el segundo es decir $p<q$
