---
title: "Determinación de la incertidumbre típica combinada"
output:
  html_document:
    toc: true
    toc_depth: 5
    
---
## Incertidumbre típica tipo B

se establecen mediante decisión científica, basada en toda la información disponible acerca de la variabilidad posible de Xi. puede comprender:

- Resultados de mediciones anteriores

- Conocimientos sobre las propiedades de los materiales e instrumentos

- Especificaciones del fabricante;

- Certificados de calibración u otros tipos de certificados;

- Incertidumbres asignadas a valores de referencia procedentes de libros y manuales.

La incertidumbre tipo B puede obtenerse de diferentes maneras

1. La estimación se obtiene a partir de una especificación del fabricante, de un certificado de
calibración,la incertidumbre viene dada como un múltiplo específico de una desviación típica, la incertidumbre típica $u(xi)$ es simplemente el cociente entre el valor indicado y el factor multiplicador, y la varianza estimada u2(xi) es el cuadrado de dicho cociente.
(ver ejemplos de la hoja y obtener la incertidumbres respectivas)




**EJEMPLO** 

Un certificado de calibración indica que la masa de un patrón de acero inoxidable, de valor nominal igual a un kilogramo, es mS = 1000,000325 g, y que “la incertidumbre de este valor es de 240 μg, para un nivel de tres desviaciones típicas”.

La incertidumbre típica del patrón de masa es simplemente u(mS) = (240 μg)/3 = 80 μg. 
Esto corresponde a una incertidumbre típica relativa u(mS)/mS de $80 × 10^-9$ . 
La varianza estimada es $u^2(mS) = (80 μg)^2 = 6,4×10^{-9} g^2.$


2. 


$u_c(y)$ es una desviación típica estimada y caracteriza la dispersión de los valores que podrían ser razonablemente atribuidos al mensurando Y. 

La incertidumbre típica combinada de y es $u_c(y)$, se obtiene de las incertidumbres típicas de las estimaciones de entrada $x_1, x_2, ..., x_N$. 



**Incertidumbre típica para magnitutes independientes**

La incertidumbre típica combinada $u_c(y)$ es la raíz cuadrada positiva de la varianza combinada $u_c^2(y)$,
dada por:

$$u_c^2(y)=\sum_{i=1}^N \left[ \frac{\partial f }{\partial x_i} \right]^2 u^2(x_i)$$


**Incertidumbre típica para magnitutes dependientes o correlacionadas**


$$u_c^2(y)=\sum_{i=1}^N \sum_{j=1}^N \frac{\partial f }{\partial x_i}\frac{\partial f }{\partial x_j}u(x_i,x_j)=\sum_{i=1}^N\left[ \frac{\partial f }{\partial x_i} \right]^2 u^2(x_i)+2\sum_{i=1}^{N-1}\sum_{j=i+1}^N \frac{\partial f }{\partial x_i} \frac{\partial f }{\partial x_j} u(x_i,x_j)$$

donde

- f es la función del mesurando dada por:

$$Y=f(X_1,X_2,...,x_n)$$


- Cada $u(xi)$ es una incertidumbre típica, (Tipo A o Tipo B). 


- Ambas ecuaciones están basadas en un desarrollo en serie de Taylor de primer orden de $Y = f(X_1, X_2, ..., X_N)$, expresan lo que en la Guía se denomina **ley de propagación de la incertidumbre.**


**Coeficientes de sensibilidad**

Las derivadas parciales $\frac{\partial f }{\partial x_i}$ calculadas para $Xi =x_i$ son denominadas coeficientes de sensibilidad, describen cómo varía la estimación de salida y, en función de las variaciones en los valores de las estimaciones de entrada $x_1, x_2, ..., x_N.$

La varianza combinada $u^2_c(y)$ puede considerarse como una suma de términos, cada uno de ellos representando la varianza estimada asociada a y, debido a la
varianza estimada asociada a cada estimación de entrada xi. Esto conduce a escribir la ecuación de la forma:



$$u_c^2(y)=\sum_{j=1}^N\left[ c_i u(x_i)\right]^2 = \sum_{i=1}^Nu^2(y)$$ 

donde 
$$c_i=\frac{\partial f }{\partial x_i}\qquad u_i(y)=|c_i|u(x_i)$$

**Ejemplo**

Si se aplica una diferencia de potencial V a los bornes de una resistencia cuyo valor depende de la temperatura, de la resistencia $R_0$ a la temperatura definida $t_0$ y del coeficiente lineal de temperatura α, la potencia disipada P (el mensurando) por la resistencia a la temperatura t es función de $V, R_0, α,$ y t, la ecuación representativa es:

$$P=f(V,R_0,\alpha,t)=\frac{V^2}{R_0[1+\alpha(t-t_0)]}$$

Las derivadas paraciales de P con respecto a cada una de las variables corresponden a :

$$c_1=\frac{\partial P }{\partial V}= \frac{2V}{R_0[1+\alpha(t-t_0)]}=\frac{2P}{V}$$
$$c_2=\frac{\partial P }{\partial R_0}= \frac{-V^2}{R_0^2[1+\alpha(t-t_0)]}=\frac{-P}{R_0}$$
$$c_3=\frac{\partial P }{\partial \alpha}= \frac{-V^2(t-t_0)}{R_0[1+\alpha(t-t_0)]^2}=\frac{-P(t-t_0)}{1+\alpha(t-t_0)}$$
$$c4=\frac{\partial P }{\partial t}= \frac{-V^2\alpha}{R_0[1+\alpha(t-t_0)]^2}=\frac{-P \alpha}{1+\alpha(t-t_0)}$$
En terminos de fórmula se traduce en:

$$u^2(P)=\left[ \frac{\partial P}{\partial V} \right]^2 u^2(V)+\left[\frac{\partial P}{\partial R_0} \right]^2u^2(R_0)+\left[ \frac{\partial P}{\partial \alpha} \right]^2u^2(\alpha)+\left[ \frac{\partial f }{\partial t} \right]^2u^2(t)$$

$$u^2(P)=\left[C_1u(V)\right]^2+\left[ C_2 u(R_0) \right]^2 +\left[ C_3u(\alpha) \right]^2+\left[C_4u(t)  \right]^2$$


