---
title: "Distribuciones de probabilidad discretas"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- [Clase de Distribuciones discretas](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/ITM_discretas.pptx)

- <a href="taller-distri.html" target="_blank"> Taller de probabilidad</a>

**Videos de interés**

*Variable aleatoria discreta*

<iframe width="280" height="160" src="https://www.youtube.com/embed/MMNVst-cEOM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="280" height="160" src="https://www.youtube.com/embed/cfNqJcNU7aI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


<iframe width="280" height="160" src="https://www.youtube.com/embed/ip-y-YW5Kg8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Propiedades de la esperanza y de la varianza*


<iframe width="280" height="160" src="https://www.youtube.com/embed/0kowS0mEOcU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="280" height="160" src="https://www.youtube.com/embed/YiHzJgg0OB8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="280" height="160" src="https://www.youtube.com/embed/I6Gcr5BUJt4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Distribuciones de probabilidad discretas 


- <a href="poisson.html" target="_blank"> Distribución poisson </a>


- <a href="binom.html" target="_blank"> Distribución binomial </a>


- <a href="hiper.html" target="_blank"> Distribución hipergeométrica </a>



**Aplicativo de distribuiones de probabilidad discretas**

```{r echo=FALSE}

knitr::include_app("  https://jtrochezg.shinyapps.io/apppoison/",height = "1000px")

```

