<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>DISEÑO FACTORIAL</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link href="site_libs/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" />
<link rel="icon" type="image/png" href="images/favicon.png" />

<script type="text/javascript" src="js/rmarkdown.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-88209726-1', 'auto');
  ga('send', 'pageview');
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Estadística ITM</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="pagin1.html">
    <span class="fas fa-line-chart"></span>
     
    Estadística Básica
  </a>
</li>
<li>
  <a href="pagin2.html">
    <span class="fas fa-bar-chart-o"></span>
     
    Estadística inferencial
  </a>
</li>
<li>
  <a href="pagin3.html">
    <span class="fas fa-pie-chart"></span>
     
    Análisis multivariado
  </a>
</li>
<li>
  <a href="about.html">
    <span class="fas fa-puzzle-piece"></span>
     
    Semillero de R
  </a>
</li>
<li>
  <a href="https://www.itm.edu.co">
    <span class="ion ion-university"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/estadisticaITM">
    <span class="fas fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">DISEÑO FACTORIAL</h1>

</div>


<ul>
<li><p>Los experimentos factoriales son aquellos en los cuales el interés se centra en el estudio de los efectos de las combinaciones de dos o más factores sobre una variable respuesta.</p></li>
<li><p>En la práctica cuando el número de factores a considerar es mayor que 3, se suelen utilizar experimentos 2k (k factores con dos niveles cada uno), experimentos 3k (k factores con tres niveles cada uno), experimentos factoriales fraccionados, etc.</p></li>
<li><p>Las unidades experimentales se considerarán homogéneas respecto a las características individuales que pudieran afectar las respuestas a los tratamientos aplicados.</p></li>
</ul>
<p>##<strong>Diseño con 2 factores</strong></p>
<p>En el caso de dos factores A y B, El número de niveles del factor A lo denotaremos por a y el número de niveles de B lo denotaremos por b.</p>
<p><strong>Definición</strong> Llamaremos tratamiento a cada combinación posible entre los niveles de los factores. Así, para el caso de dos factores, se tendrá un total de ab posibles tratamientos. Por ejemplo, sea a=3 y b=2:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th>Niveles factor B</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Niveles factor A</td>
<td>B1</td>
<td>B2</td>
</tr>
<tr class="even">
<td>A1</td>
<td>A1B1</td>
<td>A1B2</td>
</tr>
<tr class="odd">
<td>A2</td>
<td>A2B1</td>
<td>A2B2</td>
</tr>
<tr class="even">
<td>A3</td>
<td>A3B1</td>
<td>A3B2</td>
</tr>
</tbody>
</table>
<p>Cada combinación AiBj con i=1,2,3 y j=1,2 define un tratamiento, entonces hay 6 posibles tratamientos correspondientes a las entradas de esta tabla.</p>
<div id="tipos-de-experimentos-factoriales-con-dos-factores" class="section level2">
<h2>Tipos de experimentos factoriales con dos factores:</h2>
<p><strong>1. De efectos fijos:</strong> Los a niveles del factor A como los b niveles del factor B son definidos a propósito por el investigador.</p>
<p><strong>2. De efectos aleatorios:</strong> Los a niveles del factor A como los b niveles del factor B son elegidos aleatoriamente dentro de una población de posibles niveles, respectivamente.</p>
<p><strong>3. De efectos mixtos:</strong> Uno de los dos factores es de efectos fijos en tanto que el otro es de efectos aleatorios.</p>
<p>En cualquiera de los anteriores casos se debe considerar el fenómeno conocido como interacción de los factores, los modelos deben iniciarse considerando la existencia de interacción y luego a través de la evidencia muestral, determinar si dicha interacción es o no significativa. Sólo si en cada tratamiento se toman réplicas (n&gt;1 observaciones por tratamiento), será posible estimar y evaluar la interacción entre los factores.</p>
<p>A cada tratamiento se asignan en forma completamente aleatorizada, n unidades experimentales obteniéndose por tanto de cada tratamiento n observaciones de la variable respuesta. En total habrán N=abn observaciones de la variable respuesta. La tabla de entrada de datos del experimento será como se presenta en la siguiente figura</p>
<p><img src="diseñofactorial_files/figure-html/unnamed-chunk-1-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Se postula el modelo con interacción, para la k-ésima respuesta en el tratamiento AiBj (nivel i del factor A combinado con nivel j del factor B), que aparece a continuación:</p>
<p><span class="math display">\[\Large Y_{ijk}=\mu+\alpha_i+\beta_j+(\alpha\beta)_{ij}+\varepsilon_{ijk}\]</span> Donde:</p>
<p><span class="math inline">\(\Large Y_{ijk}\)</span> Variable respuesta</p>
<p><span class="math inline">\(\Large \mu\)</span> Media global de la respuesta</p>
<p><span class="math inline">\(\Large \alpha_i\)</span> Efecto fijo del i-ésimo nivel del factor A sobre la respuesta promedio global.</p>
<p><span class="math inline">\(\Large \beta_j\)</span> Efecto fijo del j-ésimo niveles del factor B sobre la respuesta promedio global.</p>
<p><span class="math inline">\(\Large \alpha_i \beta_j\)</span> Efecto fijo de la interacción de los factores A y B en sus niveles i y j, respectivamente, sobre la respuesta promedio global.</p>
<p><span class="math inline">\(\Large \varepsilon_{ijk}\)</span> error aleatorio</p>
<p><strong>Supuestos y restricciones</strong></p>
<p><span class="math display">\[\Large \varepsilon_{ij} \sim N(0,\sigma^2)\]</span> para todo i, j, k</p>
<p><span class="math display">\[\Large \sum_{i=1}^a\alpha_i=0\]</span> <span class="math display">\[\Large \sum_{j=1}^b\beta_j=0\]</span></p>
<p><span class="math display">\[\Large \sum_{i=1}^a(\alpha\beta)_{ij}=0\]</span></p>
<p><span class="math display">\[\Large \sum_{j=1}^b(\alpha\beta)_{ij}=0\]</span></p>
<p><strong>Parámetros del modelo</strong></p>
<p>Efectos de tratamientos <span class="math display">\[\Large \tau_{ij}=\alpha_i+\beta_j+(\alpha\beta)_{ij}\]</span> Representa el efecto del tratamiento AiBj sobre la respuesta promedio global.</p>
<p>Note que:</p>
<p><span class="math display">\[\Large \sum_{i=1}^a\sum_{j=1}^b\tau_{ij}=0\]</span> <strong>Medias de tratamientos:</strong></p>
<p><span class="math inline">\(\Large \mu_{ij}=\mu+\tau_{ij}\)</span> de donde <span class="math inline">\(\Large \tau_{ij}=\mu_{ij}-\mu\)</span>$</p>
<p><strong>Media del nivel i del factor A</strong></p>
<p><span class="math inline">\(\Large \mu_{i\bullet}=\mu+\alpha_i\)</span> de donde <span class="math inline">\(\Large \alpha_{i}=\mu_{i\bullet}-\mu\)</span>. Note que <span class="math inline">\(\Large \mu_{i\bullet}=\frac{1}{b}\sum_{j=1}^b \mu_{ij}\)</span></p>
<p><strong>Media del nivel j del factor B</strong></p>
<p><span class="math inline">\(\Large \mu_{\bullet j}=\mu+\beta_j\)</span> de donde <span class="math inline">\(\Large \beta_{j}=\mu_{\bullet j}-\mu\)</span>. Note que <span class="math inline">\(\Large \mu_{\bullet j}=\frac{1}{a}\sum_{i=1}^a \mu_{ij}\)</span></p>
<p><strong>Media global</strong> <span class="math display">\[\Large \mu_{\bullet }=\frac{1}{ab}\sum_{i=1}^a \sum_{j=1}^b \mu_{ij}\]</span> <strong>Efectos de interacción</strong></p>
<p><span class="math display">\[\Large (\alpha\beta)_{ij}=\mu_{ij}-\mu_{i\bullet}-\mu_{\bullet j}+\mu \]</span></p>
<p>##<strong>Interacción</strong></p>
<p>La interacción de dos factores significa que las diferencias entre las medias de tratamientos según los niveles de un factor varían (bien sea en dimensión y/o signo) de nivel a nivel del otro factor.</p>
<p>Para analizar los cambios de la respuesta promedio de cada tratamiento, se usan los gráficos de perfiles de medias o <strong>Gráficos de interacción</strong> en los cuales se presentan las medias de tratamiento en cada uno de los niveles de uno de los factores fijando los niveles del otro factor ubicado en el eje horizontal.</p>
<p><strong>Diagnóstico de la presencia de interacción</strong></p>
<p>Muestralmente podemos establecer la presencia de interacción mediante una de las siguientes formas equivalentes:</p>
<ul>
<li><p>Si se observa que los gráficos de perfiles de medias muestrales de tratamientos no son paralelos.</p></li>
<li><p>Si la diferencia entre las respuestas medias para cualesquiera dos niveles del factor A no es la misma para todos los niveles de B.</p></li>
<li><p>Si la diferencia entre las respuestas medias para cualesquiera dos niveles del factor B no es la misma para todos los niveles de A.</p></li>
<li><p>Si las medias de tratamientos no son todas iguales a la suma de la media global más los respectivos efectos principales de los factores A y B</p></li>
</ul>
<p><strong>Encubrimiento o enmascaramiento de efectos principales:</strong></p>
<p>Los efectos <span class="math inline">\(\Large \alpha_i\)</span> y <span class="math inline">\(\Large \beta_j\)</span> constituyen los efectos principales del modelo. Cuando los efectos de interacción son significativos, pueden encubrir o enmascarar a los efectos principales de uno o de ambos factores, esto significa que en las pruebas F asociadas a la significancia simultánea de los efectos del respectivo factor, no se rechaza la hipótesis nula, es decir, se concluye que el factor A, o el B o ambos, no son significativos, cuando ya se ha probado que estos interactúan significativamente.</p>
<p>Pero tenga en cuenta que, en presencia de interacción significativa, no se puede concluir que alguno o ambos factores son no significativos a pesar de que el respectivo test de significancia individual para cada factor arroje como resultado la no significancia, porque tal evento es consecuencia de un encubrimiento debido a la interacción.</p>
<p>##<strong>EJEMPLO</strong></p>
<p>La siguiente tabla muestra los resultados de un experimento factorial llevado a cabo por Derringer (1974) para determinar el efecto de los compuestos de elastómero sobre la viscosidad del sílice a 100 C. Los compuestos de elastómero estudiados fueron aceite de nafteno, en 4 niveles, y contenido de relleno (phr), en 6 niveles</p>
<table>
<thead>
<tr class="header">
<th>Nafteno (phr)</th>
<th>0</th>
<th>12</th>
<th>24</th>
<th>36</th>
<th>48</th>
<th>60</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>25</td>
<td>30</td>
<td>35</td>
<td>40</td>
<td>50</td>
<td>60</td>
</tr>
<tr class="even">
<td>10</td>
<td>18</td>
<td>21</td>
<td>24</td>
<td>28</td>
<td>33</td>
<td>41</td>
</tr>
<tr class="odd">
<td>20</td>
<td>13</td>
<td>15</td>
<td>17</td>
<td>20</td>
<td>24</td>
<td>29</td>
</tr>
<tr class="even">
<td>30</td>
<td>11</td>
<td>14</td>
<td>15</td>
<td>17</td>
<td>18</td>
<td>25</td>
</tr>
</tbody>
</table>
<pre><code>## The following objects are masked _by_ .GlobalEnv:
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 9):
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 16):
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 23):
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 30):
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 37):
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 43):
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 49):
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 55):
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 61):
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 68):
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 80):
## 
##     fill1, naft, resp</code></pre>
<pre><code>## The following objects are masked from d1 (pos = 88):
## 
##     fill1, naft, resp</code></pre>
<p><img src="diseñofactorial_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre><code>## NULL</code></pre>
<p>De la figura anterior se observa que:</p>
<ul>
<li><p>A medida que el relleno aumenta de 0 a 60, la viscosidad aumenta a lo largo de una tendencia bastante lineal.</p></li>
<li><p>Cuando no se agrega aceite de nafteno, aumentar el relleno de 0 a 60 hace que la viscosidad aumente rápidamente de 25 a 60.</p></li>
<li><p>la pendiente de la línea de tendencia depende del nivel de aceite de nafteno.</p></li>
</ul>
</div>
<div id="análisis-de-varianza" class="section level2">
<h2><strong>Análisis de Varianza</strong></h2>
<p>Para el ANOVA tendremos en cuenta los siguientes estadísticos muestrales:</p>
<table>
<colgroup>
<col width="37%" />
<col width="15%" />
<col width="46%" />
</colgroup>
<thead>
<tr class="header">
<th>Parámetro</th>
<th>Estimador</th>
<th>Observación sobre el estimador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Media global <span class="math inline">\(\Large \mu\)</span></td>
<td><span class="math inline">\(\Large \bar Y_{\bullet \bullet \bullet}=\frac{1}{abn} \sum_{i=1}^a \sum_{j=1}^b \sum_{k=1}^n Y_{ijk}\)</span></td>
<td>Promedio de todas las abn observaciones</td>
</tr>
<tr class="even">
<td>Media del tratamiento AiBj <span class="math inline">\(\Large \mu_{ij}\)</span></td>
<td><span class="math inline">\(\Large \bar Y_{ij \bullet}=\frac{1}{n} \sum_{k=1}^n Y_{ijk}\)</span></td>
<td>Promedio de las observaciones en la celda i,j</td>
</tr>
<tr class="odd">
<td>Media del nivel i del factor A <span class="math inline">\(\Large \mu_{i\bullet}\)</span></td>
<td><span class="math inline">\(\Large \bar Y_{i \bullet \bullet}=\frac{1}{bn} \sum_{j=1}^b \sum_{k=1}^n Y_{ijk}\)</span></td>
<td>Promedio de las observaciones en la fila i</td>
</tr>
<tr class="even">
<td>Media del nivel j del factor B <span class="math inline">\(\Large \mu_{\bullet j}\)</span></td>
<td><span class="math inline">\(\Large \bar Y_{\bullet j \bullet}=\frac{1}{an} \sum_{i=1}^a \sum_{k=1}^n Y_{ijk}\)</span></td>
<td>Media de las observaciones en la columna j</td>
</tr>
</tbody>
</table>
<p>El ANOVA descompone la variabilidad total de la siguiente manera:</p>
<p>SST = SSA+ SSB + SS (AB) + SSE</p>
<table>
<colgroup>
<col width="17%" />
<col width="19%" />
<col width="18%" />
<col width="18%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th>Fuente de variación</th>
<th>Grados de libertad</th>
<th>Suma de cuadrados</th>
<th>cuadrados medios</th>
<th>Valores esperados</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Factor A</td>
<td>a-1</td>
<td>SSA</td>
<td><span class="math inline">\(\Large MSA=SSA/(a-1)\)</span></td>
<td><span class="math inline">\(\Large E(MSA)=\sigma^2+bn\frac{\sum_{i=1}^a\alpha_i^2}{a-1}\)</span></td>
</tr>
<tr class="even">
<td>Factor B</td>
<td>b-1</td>
<td>SSB</td>
<td><span class="math inline">\(\Large MSB=SSB/(b-1)\)</span></td>
<td><span class="math inline">\(\Large E(MSB)=\sigma^2+an\frac{\sum_{j=1}^b\beta_i^2}{a-1}\)</span></td>
</tr>
<tr class="odd">
<td>Interacción AB</td>
<td>(a-1)(b-1)</td>
<td>SS(AB)</td>
<td><span class="math inline">\(\Large MS(AB)=SS(AB)/(a-1)(b-1)\)</span></td>
<td><span class="math inline">\(\Large E(MS(AB))=\sigma^2+n\frac{\sum_{i=1}^a\sum_{j=1}^b(\alpha \beta)_{ij}^2}{(a-1)(b-1)}\)</span></td>
</tr>
<tr class="even">
<td>Error</td>
<td>ab(n-1)</td>
<td>SSE</td>
<td><span class="math inline">\(\Large MSE=SSE/ab(n-1)\)</span></td>
<td><span class="math inline">\(E(MSE)=\sigma^2\)</span></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>abn-1</td>
<td>SST</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Fórmulas</strong></p>
<p>Las sumas de cuadrados del modelo ANOVA SST=SSA+SSB+SSE</p>
<p><span class="math display">\[\Large SST=\sum_{i=1}^a \sum_{j=1}^{b}(Y_{ij}-\bar{Y}_{\bullet \bullet})^2=\sum_{i=1}^a \sum_{j=1}^{n_i} Y^2_{ij}-ab\bar{Y}_{\bullet \bullet}^2 \]</span></p>
<p>-La variabilidad en la respuesta explicada por el factor A, con a -1 grados de libertad, está dada por:</p>
<p><span class="math display">\[\Large SSA=\sum_{i=1}^a \sum_{j=1}^{b}(Y_{i\bullet}-\bar{Y}_{\bullet \bullet})^2=b\sum_{i=1}^a \bar{Y^2_{i\bullet}}-ab\bar{Y}_{\bullet \bullet}^2 \]</span></p>
<p>-La variabilidad en la respuesta explicada por el bloque B, con b-1 grados de libertad, está dada por:</p>
<p><span class="math display">\[\Large SSB=\sum_{i=1}^a \sum_{j=1}^{b}(Y_{\bullet j}-\bar{Y}_{\bullet \bullet})^2=a\sum_{i=1}^a \bar{Y^2_{\bullet j}}-ab\bar{Y}_{\bullet \bullet}^2 \]</span></p>
<ul>
<li>La variabilidad en la respuesta explicada por la aleatoriedad, con (a-1)(b-1) grados de libertad, está dada por</li>
</ul>
<p><span class="math display">\[\Large SSE=SST-SSA-SSB\]</span></p>
<p>La media muestral en el nivel i del factor de tratamiento está dada por: <span class="math display">\[\Large \hat {\mu}_i=\bar{Y}_{i \bullet}=\frac{1}{b} \sum_{j=1}^b Y_{ij}\]</span></p>
<p>La media muestral en el nivel j del bloque está dada por:</p>
<p><span class="math display">\[\Large \hat {\mu}_j=\bar{Y}_{ \bullet j }=\frac{1}{a} \sum_{j=1}^a Y_{ij}\]</span></p>
<p><strong>Hipótesis de interés</strong></p>
<p>##<strong>Significancia de la interacción AB</strong> La prueba de hipótesis asociada al ANOVA esta dado por:</p>
<ul>
<li><strong>Juego de hipótesis</strong></li>
</ul>
<p><span class="math inline">\(\Large H_0=(\alpha \beta)_{11}=(\alpha \beta)_{12}=...=(\alpha \beta)_{ab}=0\)</span></p>
<p><span class="math inline">\(\Large H_1=(\alpha \beta)_{11}\not =(\alpha \beta)_{12}\not =...=(\alpha \beta)_{ab}\not =0\)</span></p>
<p>Con i=1,2,…a, j=1,2,…b</p>
<ul>
<li><strong>Estadístico de prueba</strong> <span class="math display">\[F_3=\frac{MS(AB)}{MSE}\sim f_{(a-1)(b-1),ab(n-1)}\]</span></li>
</ul>
<p>Si la interacción es significativa (es decir, se rechaza H0), proceder con precaución en la interpretación de los resultados de los tests de significancia sobre los efectos principales:</p>
<p>##<strong>Significancia del efecto A</strong> La prueba de hipótesis asociada al ANOVA esta dado por:</p>
<ul>
<li><strong>Juego de hipótesis</strong></li>
</ul>
<p><span class="math inline">\(\Large H_0=\alpha_{1}=\alpha_{2}=...=\alpha_{a}=0\)</span></p>
<p><span class="math inline">\(\Large H_1=\alpha_{1}\not =\alpha_{2}\not =...\not =\alpha_{a}\not =0\)</span></p>
<p>Con i=1,2,…a</p>
<ul>
<li><strong>Estadístico de prueba</strong> <span class="math display">\[F_3=\frac{MSA}{MSE}\sim f_{(a-1),ab(n-1)}\]</span></li>
</ul>
<p>Si no se rechaza <span class="math inline">\(H_o\)</span> bajo interacción significativa, hay encubrimiento de los efectos principales de este factor por parte de la interacción.</p>
<p>##<strong>Significancia del efecto B</strong> La prueba de hipótesis asociada al ANOVA esta dado por:</p>
<ul>
<li><strong>Juego de hipótesis</strong></li>
</ul>
<p><span class="math inline">\(\Large H_0=\beta_{1}=\beta_{2}=...=\beta_{a}=0\)</span></p>
<p><span class="math inline">\(\Large H_1=\beta_{1}\not =\beta_{2}\not =...\not =\beta_{a}\not =0\)</span></p>
<p>Con j=1,2,…b</p>
<ul>
<li><strong>Estadístico de prueba</strong> <span class="math display">\[F_3=\frac{MSA}{MSE}\sim f_{(b-1),ab(n-1)}\]</span></li>
</ul>
<p>Si no se rechaza <span class="math inline">\(H_o\)</span> bajo interacción significativa, hay encubrimiento de los efectos principales de este factor por parte de la interacción.</p>
<p><strong>Modelo sin interacción</strong> En caso de que los datos obtenidos presenten evidencia respecto a la no significancia del término de interacción, el modelo factorial debe replantearse de la siguiente manera:</p>
<p><span class="math display">\[\Large Y_{ijk}=\mu+\alpha_i+\beta_j+(\alpha\beta)_{ij}+\varepsilon_{ijk}\]</span></p>
<p>##<strong>Diseños factoriales con tres factores</strong></p>
<ul>
<li>El estudio factorial de tres factores A, B y C permite estudiar los efectos A, B, C (efectos principales), AB, AC, BC (efectos de las interacciones de a dos factores) y ABC (la triple interacción), donde el grado de detalle con el que se puede estudiar depende del número de niveles usados para cada factor.</li>
</ul>
<p>Por ejemplo, para un factor con dos niveles no es posible descomponer su efecto individual; pero si se toman tres niveles el efecto individual de un factor puede descomponerse en una parte lineal y una cuadrática.</p>
<p>Sean a, b, y c el número de niveles usados de los factores A, B y C respectivamente y n el número de réplicas en cada tratamiento (combinaciones de niveles de los tres factores). Se tendrá entonces la siguiente tabla ANOVA:</p>
<p><img src="diseñofactorial_files/figure-html/unnamed-chunk-3-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Se postula el modelo con interacción, para la k-ésima respuesta en el tratamiento AiBj (nivel i del factor A combinado con nivel j del factor B), que aparece a continuación:</p>
<p><span class="math display">\[\Large Y_{ijk}=\mu+\alpha_i+\beta_j+\lambda_k+(\alpha\beta)_{ij}+(\alpha\lambda)_{ik}+(\beta\lambda)_{jk}+(\alpha\beta\lambda)_{ijk}+\varepsilon_{ijk}\]</span></p>
<p><span class="math inline">\(\Large \alpha_i, \beta_j, \lambda_k\)</span> denotan los efectos sobre la respuesta promedio global de los factores A, B y C en sus niveles i, j k respectivamente.</p>
<p><span class="math inline">\(\Large (\alpha\beta)_{ij},(\alpha\lambda)_{ik}\)</span> y $ ()_{jk}$ son los efectos de las interacciones de a dos factores</p>
<p><span class="math inline">\(\Large (\alpha\beta \lambda)_{ijk}\)</span> es la interacción triple,</p>
<p><strong>Supuestos y restricciones</strong></p>
<p><span class="math display">\[\Large \varepsilon_{ijkl} \sim N(0,\sigma^2)\]</span> para todo i, j, k</p>
<p><span class="math display">\[\Large \sum_{i=1}^a\alpha_i=\sum_{j=1}^b\beta_j=\sum_{k=1}^c
\lambda_k=0\]</span></p>
<p><span class="math display">\[\Large \sum_{i=1}^a\sum_{j=1}^b(\alpha\beta)_{ij}=0\]</span></p>
<p><span class="math display">\[\Large \sum_{j=1}^b\sum_{k=1}^c(\alpha\lambda)_{ik}=0\]</span></p>
<ul>
<li><p>El análisis de la significancia de los efectos de este modelo debe realizarse en forma jerárquica partiendo de los efectos de interacción de mayor orden.</p></li>
<li><p>Ningún efecto principal o de interacción de dos factores puede eliminarse de un modelo mientras la triple interacción sea significativa.</p></li>
<li><p>En general, ningún factor deberá descartarse del modelo mientras participe en efectos de interacción de cualquier orden que sean significativos.</p></li>
<li><p>En el caso que ni sus efectos de interacción ni sus efectos principales resulten significativos, se podrá concluir que tal factor no incide sobre el promedio de la respuesta.</p></li>
</ul>
<p><strong>Procedimiento</strong> <strong>Paso 1:</strong> <span class="math inline">\(H_0=(\alpha\beta\lambda)_{111}=...=(\alpha\beta\lambda)_{abc}\)</span> si no se rechaza <span class="math inline">\(H_0\)</span> relice la siguiente prueba</p>
<p><strong>Paso 2:</strong> evaluar la prueba de hipótesis de las interacciones</p>
<p><strong>Paso 3:</strong> Realizar las pruebas de cada factor sólo para los factores no involucrados en interacciones significativas de ningún orden (dobles o triple).</p>
<p>##<strong>Comparación de medias ante la presencia de interacción</strong></p>
<p>La estimación de un efecto principal es una diferencia promediada o contraste entre todas las medias de los niveles del factor correspondiente, por ello al hacer inferencias sobre tales medias con base en las estimaciones de los efectos principales, en presencia de interacción, es realizar una generalización sobre los niveles del factor, y por tanto dichas inferencias estarán equivocadas.</p>
<p>Una comparación generalizada entre las medias de un factor tiene sentido si las diferencias existentes entre dichas medias se sostienen de nivel a nivel del otro factor, es decir, cuando no hay interacción. De lo contrario, lo mejor es realizar comparaciones y contrastes de medias de tratamientos <span class="math inline">\(\Large \mu_{ij}\)</span> que ayuden a interpretar los efectos significativos de la interacción. Así ante interacción, sería más conveniente comparar las medias de dicho factor pero en cada uno de los niveles del otro factor. Por ejemplo, suponga un experimento con a=3 y b=2 en el cual los datos evidencian interacción significativa pero aparentemente el factor A no es significativo; en este caso sería conveniente realizar pruebas como las siguientes:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th>Niveles factor B</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Niveles factor A</td>
<td>B1</td>
<td>B2</td>
</tr>
<tr class="even">
<td>A1</td>
<td>A1B1</td>
<td>A1B2</td>
</tr>
<tr class="odd">
<td>A2</td>
<td>A2B1</td>
<td>A2B2</td>
</tr>
<tr class="even">
<td>A3</td>
<td>A3B1</td>
<td>A3B2</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha">
<li>Comparar medias de A en el nivel 1 de B</li>
</ol>
<p><span class="math inline">\(\Large H_0=\mu{11}=\mu_{21}=\mu_{31}\)</span></p>
<p><span class="math inline">\(\Large H_1=\mu{11}\not =\mu_{21}\not =\mu_{31}\)</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Comparar medias de A en el nivel 2 de B</li>
</ol>
<p><span class="math inline">\(\Large H_0=\mu{12}=\mu_{22}=\mu_{32}\)</span></p>
<p><span class="math inline">\(\Large H_1=\mu{12}\not =\mu_{22}\not =\mu_{32}\)</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Comparar medias de B en el nivel 1 de A</li>
</ol>
<p><span class="math inline">\(\Large H_0=\mu{11}=\mu_{12}\)</span></p>
<p><span class="math inline">\(\Large H_1=\mu{11}\not =\mu_{12}\)</span></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Comparar medias de B en el nivel 2 de A</li>
</ol>
<p><span class="math inline">\(\Large H_0=\mu{21}=\mu_{22}\)</span></p>
<p><span class="math inline">\(\Large H_1=\mu{21}\not =\mu_{22}\)</span></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Comparar medias de B en el nivel 1 de A</li>
</ol>
<p><span class="math inline">\(\Large H_0=\mu{31}=\mu_{32}\)</span></p>
<p><span class="math inline">\(\Large H_1=\mu{31}\not =\mu_{32}\)</span></p>
<p>Ante interacción no se recomienda realizar comparaciones de Tukey sobre las medias de cada factor. Tukey podría aplicarse más bien a las medias de un factor en cada nivel del otro. Por ejemplo para comparar todas las medias de A en el nivel Bj, es decir las medias <span class="math inline">\(\Large \mu_{1j},\mu_{2j}...\mu_{aj}\)</span>.</p>
<p><strong>Ejemplo de un diseño con dos factores de efectos fijos</strong> El personal de un centro de servicio electrónico incluye tres técnicos especializados en reparar las tres marcas más usadas de unidades de disquetes para micro computadores. Se desea estudiar los efectos del factor TECNICO y del factor MARCA de la unidad de disquete, sobre el tiempo de servicio dado en minutos. A cada técnico se le asignaron aleatoriamente cinco trabajos de cada una de las marcas y se registro el número de minutos requerido para completar cada trabajo.</p>
<table>
<thead>
<tr class="header">
<th>Técnico</th>
<th>Marca 1</th>
<th>Marca 2</th>
<th>Marca3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>62</td>
<td>57</td>
<td>59</td>
</tr>
<tr class="even">
<td>1</td>
<td>48</td>
<td>45</td>
<td>53</td>
</tr>
<tr class="odd">
<td>1</td>
<td>63</td>
<td>39</td>
<td>67</td>
</tr>
<tr class="even">
<td>1</td>
<td>57</td>
<td>54</td>
<td>66</td>
</tr>
<tr class="odd">
<td>1</td>
<td>69</td>
<td>44</td>
<td>47</td>
</tr>
<tr class="even">
<td>2</td>
<td>51</td>
<td>61</td>
<td>55</td>
</tr>
<tr class="odd">
<td>2</td>
<td>57</td>
<td>58</td>
<td>58</td>
</tr>
<tr class="even">
<td>2</td>
<td>45</td>
<td>70</td>
<td>50</td>
</tr>
<tr class="odd">
<td>2</td>
<td>50</td>
<td>66</td>
<td>69</td>
</tr>
<tr class="even">
<td>2</td>
<td>39</td>
<td>51</td>
<td>49</td>
</tr>
<tr class="odd">
<td>3</td>
<td>59</td>
<td>58</td>
<td>47</td>
</tr>
<tr class="even">
<td>3</td>
<td>65</td>
<td>63</td>
<td>56</td>
</tr>
<tr class="odd">
<td>3</td>
<td>55</td>
<td>70</td>
<td>51</td>
</tr>
<tr class="even">
<td>3</td>
<td>52</td>
<td>53</td>
<td>44</td>
</tr>
<tr class="odd">
<td>3</td>
<td>70</td>
<td>60</td>
<td>50</td>
</tr>
</tbody>
</table>
<p>Las gráficas y tablas siguientes representan el análisis de varianza realizado. 1. Defina claramente el modelo de análisis de varianza requerido para estudiar este problema.</p>
<p>Se postula el modelo con interacción, para la k-ésima respuesta en el tratamiento AiBj (nivel i del factor A combinado con nivel j del factor B), que aparece a continuación:</p>
<p><span class="math display">\[\Large Y_{ijk}=\mu+\alpha_i+\beta_j+(\alpha\beta)_{ij}+\varepsilon_{ijk}\]</span> donde tomando como factor A: TECNICO y B: MARCA, con niveles a=3 y b=3 respectivamente y n=5,</p>
<p><span class="math inline">\(\Large Y_{ijk}\)</span> tiempo de reparación en la k-ésima unidad de la marca j con técnico i</p>
<p><span class="math inline">\(\Large \mu\)</span> es el promedio global del tiempo de reparación de una unidad</p>
<p><span class="math inline">\(\Large \alpha_i\)</span> es el efecto del técnico i sobre el promedio global del tiempo de reparación de una unidad.</p>
<p><span class="math inline">\(\Large \beta_j\)</span> es el efecto de la marca j sobre el promedio global del tiempo de reparación de una unidad.</p>
<p><span class="math inline">\(\Large \alpha_i \beta_j\)</span> es el efecto de la interacción del técnico i con la marca j sobre el promedio global del tiempo de reparación de una unidad</p>
<p><span class="math inline">\(\Large \varepsilon_{ijk}\)</span> es el error aleatorio en la k-ésima réplica del tratamiento ij</p>
<p><strong>Supuestos y restricciones</strong></p>
<p><span class="math display">\[\Large \varepsilon_{ij} \sim N(0,\sigma^2)\]</span> para todo i, j, k</p>
<p><span class="math display">\[\Large \sum_{i=1}^3\alpha_i=\sum_{j=1}^3\beta_j=\sum_{i=1}^3(\alpha\beta)_{ij}=\sum_{j=1}^3(\alpha\beta)_{ij}=0\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Haga un análisis descriptivo de los datos.</li>
</ol>
<pre><code>## The following objects are masked _by_ .GlobalEnv:
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 4):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 6):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 7):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 8):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 9):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 11):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 13):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 14):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 15):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 16):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 18):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 20):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 21):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 22):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 23):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 25):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 27):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 28):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 29):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 30):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 32):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 34):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 35):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 36):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 37):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 39):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 40):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 41):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 42):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 43):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 45):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 46):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 47):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 48):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 49):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 51):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 52):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 53):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 54):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 55):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 57):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 58):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 59):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 60):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 61):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 63):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 65):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 66):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 67):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 68):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 70):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 77):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 78):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 79):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 80):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 82):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 85):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 86):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 87):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 88):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 90):
## 
##     tiempo</code></pre>
<p><img src="diseñofactorial_files/figure-html/unnamed-chunk-4-1.png" width="672" /><img src="diseñofactorial_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre><code>##   marca tecnico tiempo
## 1     1       1   59.8
## 2     2       1   47.8
## 3     3       1   58.4
## 4     1       2   48.4
## 5     2       2   61.2
## 6     3       2   56.2
## 7     1       3   60.2
## 8     2       3   60.8
## 9     3       3   49.6</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Determine si la interacción es significativa. Escriba la expresión empleada para calcular el valor p. Emplee un nivel de significancia de 0.05 en todas las pruebas.</li>
</ol>
<pre><code>## The following objects are masked _by_ .GlobalEnv:
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 3):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 5):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 7):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 8):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 9):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 10):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 12):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 14):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 15):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 16):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 17):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 19):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 21):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 22):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 23):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 24):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 26):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 28):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 29):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 30):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 31):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 33):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 35):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 36):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 37):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 38):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 40):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 41):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 42):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 43):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 44):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 46):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 47):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 48):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 49):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 50):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 52):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 53):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 54):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 55):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 56):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 58):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 59):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 60):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 61):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 62):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 64):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 66):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 67):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 68):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 69):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 71):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 78):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 79):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 80):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 81):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 83):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 86):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 87):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 88):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 89):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 91):
## 
##     tiempo</code></pre>
<pre><code>##               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## marca          2   28.3   14.16   0.272 0.763283    
## tecnico        2   24.6   12.29   0.236 0.790779    
## marca:tecnico  4 1215.3  303.82   5.841 0.000994 ***
## Residuals     36 1872.4   52.01                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>##<strong>Significancia de la interacción AB</strong> La prueba de hipótesis asociada al ANOVA esta dado por:</p>
<ul>
<li><strong>Juego de hipótesis</strong> La interacción entre técnico y marca no es significativa:</li>
</ul>
<p><span class="math inline">\(\Large H_0=(\alpha \beta)_{11}=(\alpha \beta)_{12}=...=(\alpha \beta)_{33}=0\)</span></p>
<p>La interacción entre técnico y marca es significativa: <span class="math inline">\(\Large H_1=(\alpha \beta)_{11}\not =(\alpha \beta)_{12}\not =...=(\alpha \beta)_{ab}\not =0\)</span></p>
<p>Con i=1,2,3, j=1,2,3</p>
<ul>
<li><strong>Estadístico de prueba</strong> <span class="math display">\[F_3=\frac{MS(AB)}{MSE}=5.84\sim f_{4,36}\]</span> <span class="math inline">\(VP=P(f_{4,36}&gt;5.84)=0.001\)</span></li>
</ul>
<p>Se concluye con una significancia de 0.05 que sí hay interacción significativa entre los factores TÉCNICO y MARCA, por lo tanto los efectos de cada factor dependen del otro. Como consecuencia de esto es necesario interpretar con precaución los resultados de los tests sobre la significancia de los efectos principales de cada factor: De hecho, si la interacción es significativa, entonces los dos factores son significativos a través de la interacción!!!.</p>
<ol start="4" style="list-style-type: decimal">
<li>Discuta la significancia de los efectos principales factores TECNICO y MARCA. En el caso de indicios de encubrimiento realice pruebas de hipótesis para confirmarlo y haga las recomendaciones.</li>
</ol>
<ul>
<li>Sobre la significancia de los efectos principales del factor TÉCNICO:</li>
</ul>
<p>Efectos principales del factor técnico no son significativos <span class="math inline">\(\Large H_0=\alpha_{1}=\alpha_{2}=\alpha_{3}=0\)</span> Algunos efectos principales del factor técnico son significativos <span class="math inline">\(\Large H_1=\alpha_{1}\not =\alpha_{2}\not =\alpha_{3}\not =0\)</span></p>
<p>O bien en terminos de las medias</p>
<p>Las medias de los tiempos de reparación según el factor técnico no difieren significativamente <span class="math inline">\(\Large H_0=\mu_{1 \bullet}=\mu_{2 \bullet}=\mu_{3\bullet}\)</span> Al menos dos de las medias de los tiempos de reparación según el factor técnico difieren significativamente <span class="math inline">\(\Large H_1 =\mu_{1 \bullet}\not=\mu_{2 \bullet}\not=\mu_{3\bullet}\)</span></p>
<ul>
<li><p><strong>Estadístico de prueba</strong> <span class="math display">\[F_3=\frac{MS(AB)}{MSE}=0.24\sim f_{2,36}\]</span> <span class="math inline">\(VP=P(f_{2,36}&gt;0.24)=0.7908\)</span></p></li>
<li><p>Sobre la significancia de los efectos principales del factor MARCA:</p></li>
</ul>
<p>Efectos principales del factor marca no son significativos <span class="math inline">\(\Large H_0=\beta_{1}=\beta_{2}=\beta_{3}=0\)</span> Algunos efectos principales del factor marca son significativos <span class="math inline">\(\Large H_1=\beta_{1}\not =\beta_{2}\not =\beta_{3}\not =0\)</span></p>
<p>O bien en terminos de las medias</p>
<p>Las medias de los tiempos de reparación según el factor marca no difieren significativamente <span class="math inline">\(\Large H_0=\mu_{\bullet 1}=\mu_{ \bullet 2}=\mu_{\bullet 3}\)</span></p>
<p>Al menos dos de las medias de los tiempos de reparación según el factor marca difieren significativamente <span class="math inline">\(\Large H_1 =\mu_{1 \bullet}\not=\mu_{2 \bullet}\not=\mu_{3\bullet}\)</span></p>
<ul>
<li><strong>Estadístico de prueba</strong> <span class="math display">\[F_3=\frac{MS(AB)}{MSE}=0.27\sim f_{2,36}\]</span> <span class="math inline">\(VP=P(f_{2,36}&gt;0.27)=0.7633\)</span></li>
</ul>
<p>Se concluye que con una significancia de 0.05, ante interacción significativa, los efectos principales del factor MARCA son enmascarados por la interacción y por lo tanto no pueden ser medidos sus efectos principales!!!. Esto quiere decir que no tiene sentido estimar ni efectos, ni medias para los niveles de MARCA y tampoco tiene sentido construir I.C, o hacer comparaciones de Tukey o contrastes con las medias de este factor. Lo más recomendable es realizar contrastes o comparaciones de medias de tratamientos de un factor en cada nivel del otro factor.</p>
<ol start="5" style="list-style-type: decimal">
<li>Construya la tabla de medias por tratamiento.</li>
</ol>
<p>Medias de tratamientos técnico*marca e I.C. del 95%.</p>
<pre><code>## The following objects are masked _by_ .GlobalEnv:
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 3):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 4):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 6):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 8):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 9):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 10):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 11):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 13):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 15):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 16):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 17):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 18):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 20):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 22):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 23):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 24):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 25):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 27):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 29):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 30):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 31):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 32):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 34):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 36):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 37):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 38):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 39):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 41):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 42):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 43):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 44):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 45):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 47):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 48):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 49):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 50):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 51):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 53):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 54):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 55):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 56):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 57):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 59):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 60):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 61):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 62):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 63):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 65):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 67):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 68):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 69):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 70):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 72):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 79):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 80):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 81):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 82):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 84):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 87):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 88):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 89):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 90):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 92):
## 
##     tiempo</code></pre>
<pre><code>##               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## marca          2   28.3   14.16   0.272 0.763283    
## tecnico        2   24.6   12.29   0.236 0.790779    
## marca:tecnico  4 1215.3  303.82   5.841 0.000994 ***
## Residuals     36 1872.4   52.01                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = tiempo ~ marca * tecnico)
## 
## $`marca:tecnico`
##          diff       lwr      upr     p adj
## 2:1-1:1 -12.0 -27.03865  3.03865 0.2095773
## 3:1-1:1  -1.4 -16.43865 13.63865 0.9999970
## 1:2-1:1 -11.4 -26.43865  3.63865 0.2658953
## 2:2-1:1   1.4 -13.63865 16.43865 0.9999970
## 3:2-1:1  -3.6 -18.63865 11.43865 0.9965056
## 1:3-1:1   0.4 -14.63865 15.43865 1.0000000
## 2:3-1:1   1.0 -14.03865 16.03865 0.9999998
## 3:3-1:1 -10.2 -25.23865  4.83865 0.4054029
## 3:1-2:1  10.6  -4.43865 25.63865 0.3552211
## 1:2-2:1   0.6 -14.43865 15.63865 1.0000000
## 2:2-2:1  13.4  -1.63865 28.43865 0.1130579
## 3:2-2:1   8.4  -6.63865 23.43865 0.6555252
## 1:3-2:1  12.4  -2.63865 27.43865 0.1771874
## 2:3-2:1  13.0  -2.03865 28.03865 0.1359755
## 3:3-2:1   1.8 -13.23865 16.83865 0.9999787
## 1:2-3:1 -10.0 -25.03865  5.03865 0.4316582
## 2:2-3:1   2.8 -12.23865 17.83865 0.9994109
## 3:2-3:1  -2.2 -17.23865 12.83865 0.9999018
## 1:3-3:1   1.8 -13.23865 16.83865 0.9999787
## 2:3-3:1   2.4 -12.63865 17.43865 0.9998112
## 3:3-3:1  -8.8 -23.83865  6.23865 0.5990906
## 2:2-1:2  12.8  -2.23865 27.83865 0.1487668
## 3:2-1:2   7.8  -7.23865 22.83865 0.7366003
## 1:3-1:2  11.8  -3.23865 26.83865 0.2273106
## 2:3-1:2  12.4  -2.63865 27.43865 0.1771874
## 3:3-1:2   1.2 -13.83865 16.23865 0.9999991
## 3:2-2:2  -5.0 -20.03865 10.03865 0.9710966
## 1:3-2:2  -1.0 -16.03865 14.03865 0.9999998
## 2:3-2:2  -0.4 -15.43865 14.63865 1.0000000
## 3:3-2:2 -11.6 -26.63865  3.43865 0.2460831
## 1:3-3:2   4.0 -11.03865 19.03865 0.9928966
## 2:3-3:2   4.6 -10.43865 19.63865 0.9825836
## 3:3-3:2  -6.6 -21.63865  8.43865 0.8715885
## 2:3-1:3   0.6 -14.43865 15.63865 1.0000000
## 3:3-1:3 -10.6 -25.63865  4.43865 0.3552211
## 3:3-2:3 -11.2 -26.23865  3.83865 0.2867388</code></pre>
<p><img src="diseñofactorial_files/figure-html/unnamed-chunk-6-1.png" width="672" /><img src="diseñofactorial_files/figure-html/unnamed-chunk-6-2.png" width="672" /><img src="diseñofactorial_files/figure-html/unnamed-chunk-6-3.png" width="672" /></p>
<p>note que en este caso no se obtienen diferencias significativas entre tratamientos, no porque no existan tales diferencias, sino porque se pierde potencia en este procedimiento con un número tan grande de comparaciones.</p>
<p>Aquí las medias de tratamiento <span class="math inline">\(\Large \mu_{11},\mu_{13}, \mu_{21},\mu_{22},\mu_{23},\mu_{31},\mu_{32},\mu_{33}\)</span> son etiquetadas, respectivamente, como <span class="math inline">\(i:j\)</span>, así, por ejemplo, en la comparación 2:1 – 1:1 hace referencia a la diferencia de las medias <span class="math inline">\(\Large \mu_{21}\)</span> y <span class="math inline">\(\Large \mu_{11}\)</span></p>
<p>La prueba de hipótesis corresponde a:</p>
<p><span class="math inline">\(\Large H_0=\)</span> Algún $<em>{ij} = </em>{ij} $ <span class="math inline">\(\Large H_1=\)</span> Algún $<em>{ij} = </em>{ij} $</p>
<ol start="6" style="list-style-type: decimal">
<li>Plantee un contraste para probar si el tiempo promedio empleado para reparar un micro de la marca 2 y uno de la marca 3 es el mismo para el técnico 2 y 3.</li>
</ol>
<p>Se pide comparar el promedio de las medias <span class="math inline">\(\Large \mu_{22}\)</span> y <span class="math inline">\(\Large \mu_{23}\)</span> es igual al promedio de las medias <span class="math inline">\(\Large \mu_{32}\)</span> y <span class="math inline">\(\Large \mu_{33}\)</span></p>
<p>El contraste indicado es <span class="math display">\[\Large W=\frac{1}{2}(\mu_{22}+\mu_{23})-\frac{1}{2}(\mu_{32}+\mu_{33})\]</span> El test de hipótesis corresponde a:</p>
<p><span class="math display">\[\Large H_o= W=0\]</span> <span class="math display">\[\Large H_1=W \not=0\]</span> Equivalentemente <span class="math display">\[\Large H_0=\mu_{22}+\mu_{23}=\mu_{32}+\mu_{33}\]</span> <span class="math display">\[\Large H_1=\mu_{22}+\mu_{23}\not =\mu_{32}+\mu_{33}\]</span></p>
<p>Como cada media <span class="math inline">\(\Large \bar y_{ij\bullet}\sim N(\mu_{ij},\frac{\sigma^2}{n})\)</span> y todas las medias muestrales de tratamiento son mutuamente independientes, entonces el estimador del contraste de medias es: <span class="math display">\[\Large \hat W=\frac{1}{2}(\bar y_{22\bullet}+\bar y_{23\bullet})-\frac{1}{2}(\bar y_{32\bullet}+\bar y _{33\bullet})\sim N (W,\sigma^2 [\frac{1}{4n}+\frac{1}{4n}+\frac{1}{4n}+\frac{1}{4n}])\]</span></p>
<p>para esta prueba se puede construir un estadístico t dado por:</p>
<p><span class="math display">\[\Large T_0=\frac{\frac{1}{2}*(\bar y_{22\bullet}+\bar y_{23\bullet})-\frac{1}{2}(\bar y_{32\bullet}+\bar y _{33\bullet})}{\sqrt{ MSE*\frac{1}{n}}}\sim t_{ab(n-1)}\]</span> y se rechazaría <span class="math inline">\(H_0\)</span> a un nivel de significancia de 0.05 si<span class="math inline">\(|T_0|&gt;t_{0.025,ab(n-1)}\)</span></p>
<p>Para la prueba en cuestión se tiene que:</p>
<p><span class="math inline">\(\Large \bar y_{22\bullet}=61.2\)</span></p>
<p><span class="math inline">\(\large \bar y_{23\bullet}=56.2\)</span></p>
<p><span class="math inline">\(\Large \bar y_{32\bullet}=60.8\)</span></p>
<p><span class="math inline">\(\Large \bar y _{33\bullet}=49.6\)</span></p>
<p><span class="math inline">\(n=5\)</span></p>
<p><span class="math inline">\(MSE=52.01\)</span></p>
<p>Luego <span class="math inline">\(T_0=1.0852\)</span> y <span class="math inline">\(t_{0.025,36}=2.028\)</span> por tanto se concluye que el tiempo promedio empleado para reparar un micro de la marca 2 y uno de la marca 3 es el mismo para el técnico 2 y 3.</p>
<ol start="7" style="list-style-type: decimal">
<li>Compare ahora las medias del factor TÉCNICO en cada nivel del factor MARCA, y viceversa. Permiten estos resultados tomar decisiones acerca del problema en cuestión? Cuáles son las recomendaciones que usted haría si quiere disminuir el tiempo de servicio del centro de servicios electrónicos.</li>
</ol>
<p>En la siguiente tabla se aprecian los resultados de los testes sobre la igualdad de las medias del factor TÉCNICO en cada nivel del factor MARCA, veamos cada una:</p>
<p>###<strong>Comparación de las medias de los técnicos a nivel de la marca 1:</strong></p>
<p>técnico,operario <span class="math inline">\(\Large H_o: \mu_{11}=\mu_{21}=\mu_{31}\)</span></p>
<p>El estadístico para probar esta hipótesis corresponde a: <span class="math display">\[\Large F_0=\frac{MS_{A|B1}}{MSE}=4.32\sim f_{a-1,ab(n-1)}\]</span></p>
<p>Donde <span class="math display">\[\Large MS_{A|B1}=n \frac {\sum_{i=1}^a(\bar y_{i1\bullet}-\bar y_{\bullet1\bullet})}{a-1}\]</span> es la suma de cuadrados medios debida al factor TÉCNICO pero correspondiente alas observaciones con la marca 1. <span class="math display">\[\Large VP=P(f_{2,36}&gt;4.32)=0.0209\]</span> Con estos resultados se concluye que a un nivel de significancia de 0.05, con la marca 1 los técnicos tardan en promedio diferente tiempo para reparar una unidad (al menos dos de ellos).</p>
<p>###<strong>Comparación de las medias de los técnicos a nivel de la marca 2:</strong></p>
<p>técnico,operario <span class="math inline">\(\Large H_o: \mu_{12}=\mu_{22}=\mu_{32}\)</span></p>
<p>El estadístico para probar esta hipótesis corresponde a: <span class="math display">\[\Large F_0=\frac{MS_{A|B2}}{MSE}=5.59\sim f_{a-1,ab(n-1)}\]</span></p>
<p>Donde <span class="math display">\[\Large MS_{A|B2}=n \frac {\sum_{i=1}^a(\bar y_{i2\bullet}-\bar y_{\bullet2\bullet})}{a-1}\]</span> es la suma de cuadrados medios debida al factor TÉCNICO pero correspondiente alas observaciones con la marca 1.</p>
<p><span class="math display">\[\Large VP=P(f_{2,36}&gt;5.59)=0.077\]</span> Con estos resultados se concluye que a un nivel de significancia de 0.05, con la marca 2 los técnicos tardan en promedio diferente tiempo para reparar una unidad (al menos dos de ellos).</p>
<p>###<strong>Comparación de las medias de los técnicos a nivel de la marca 3:</strong></p>
<p>técnico,operario <span class="math inline">\(\Large H_o: \mu_{13}=\mu_{23}=\mu_{33}\)</span></p>
<p>El estadístico para probar esta hipótesis corresponde a: <span class="math display">\[\Large F_0=\frac{MS_{A|B3}}{MSE}=2.02\sim f_{a-1,ab(n-1)}\]</span></p>
<p>Donde <span class="math display">\[\Large MS_{A|B3}=n \frac {\sum_{i=1}^a(\bar y_{i3\bullet}-\bar y_{\bullet 3 \bullet})}{a-1}\]</span> es la suma de cuadrados medios debida al factor TÉCNICO pero correspondiente alas observaciones con la marca 1.</p>
<p><span class="math display">\[\Large VP=P(f_{2,36}&gt;2.02)=0.1479\]</span> Con estos resultados se concluye que a un nivel de significancia de 0.05, con la marca 3 los técnicos tardan en promedio el mismo tiempo para reparar una unidad. Sin embargo mire en la figura 3 estas tres medias y en el numeral 5.3 los valores de las medias estimadas que corresponden a <span class="math inline">\(\bar y_{13\bullet}=58.4, \bar y _{23\bullet}=56.2\)</span> y <span class="math inline">\(\bar y_{33\bullet}=49.6\)</span> , hay una diferencia de 8.8 y 6.6 minutos de las dos primeras medias respecto a la última; la pregunta es si en términos prácticos tales diferencias son o no significativas, a pesar que no se encuentra significancia estadística!!!</p>
<p><strong>Comparación de las medias de las marcas a nivel de cada técnico</strong></p>
<p>En la siguiente tabla precedente se aprecian los resultados de los pruebas sobre la igualdad de las medias del factor MARCA en cada nivel del factor TÉCNICO, veamos cada una:</p>
<p><strong>Comparación de las medias de las marcas a nivel del técnico 1:</strong></p>
<p>técnico,operario <span class="math inline">\(\Large H_o: \mu_{11}=\mu_{12}=\mu_{13}\)</span></p>
<p>El estadístico para probar esta hipótesis corresponde a: <span class="math display">\[\Large F_0=\frac{MS_{B|A1}}{MSE}=4.14\sim f_{b-1,ab(n-1)}\]</span></p>
<p>Donde <span class="math display">\[\Large MS_{B|A1}=n \frac {\sum_{i=1}^a(\bar y_{1j\bullet}-\bar y_{1\bullet\bullet})}{b-1}\]</span> es la suma de cuadrados medios debida al factor marca pero correspondiente a las observaciones con el técnico 1.</p>
<p><span class="math display">\[\Large VP=P(f_{2,36}&gt;4.14)=0.0241\]</span></p>
<p>Con estos resultados se concluye que a un nivel de significancia de 0.05, con el técnico 1 los tiempos promedios de reparación por unidad de al menos dos de las tres marcas son diferentes.</p>
<p><strong>Comparación de las medias de las marcas a nivel del técnico 2:</strong></p>
<p>técnico,operario <span class="math inline">\(\Large H_o: \mu_{21}=\mu_{22}=\mu_{23}\)</span></p>
<p>El estadístico para probar esta hipótesis corresponde a: <span class="math display">\[\Large F_0=\frac{MS_{B|A2}}{MSE}=4\sim f_{b-1,ab(n-1)}\]</span></p>
<p>Donde <span class="math display">\[\Large MS_{B|A2}=n \frac {\sum_{i=1}^a(\bar y_{2j\bullet}-\bar y_{2\bullet\bullet})}{b-1}\]</span> es la suma de cuadrados medios debida al factor marca pero correspondiente a las observaciones con el técnico 2.</p>
<p><span class="math display">\[\Large VP=P(f_{2,36}&gt;4.14)=0.0241\]</span></p>
<p>Con estos resultados se concluye que a un nivel de significancia de 0.05, con el técnico 2 los tiempos promedios de reparación por unidad de al menos dos de las tres marcas son diferentes.</p>
<p><strong>Comparación de las medias de las marcas a nivel del técnico 3:</strong> técnico,operario <span class="math inline">\(\Large H_o: \mu_{31}=\mu_{32}=\mu_{33}\)</span></p>
<p>El estadístico para probar esta hipótesis corresponde a: <span class="math display">\[\Large F_0=\frac{MS_{B|A3}}{MSE}=3.82\sim f_{b-1,ab(n-1)}\]</span></p>
<p>Donde: <span class="math display">\[\Large MS_{B|A3}=n \frac {\sum_{i=1}^a(\bar y_{3j\bullet}-\bar y_{3\bullet\bullet})}{b-1}\]</span> es la suma de cuadrados medios debida al factor marca pero correspondiente a las observaciones con el técnico 3.</p>
<p><span class="math display">\[\Large VP=P(f_{2,36}&gt;3.82)=0.0314\]</span></p>
<p>Con estos resultados se concluye que a un nivel de significancia de 0.05, con el técnico 3 los tiempos promedios de reparación por unidad de al menos dos de las tres marcas son diferentes.</p>
<pre><code>## The following objects are masked _by_ .GlobalEnv:
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 3):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 4):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 5):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 7):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 9):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 10):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 11):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 12):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 14):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 16):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 17):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 18):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 19):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 21):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 23):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 24):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 25):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 26):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 28):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 30):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 31):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 32):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 33):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 35):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 37):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 38):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 39):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 40):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 42):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 43):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 44):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 45):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 46):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 48):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 49):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 50):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 51):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 52):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 54):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 55):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 56):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 57):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 58):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 60):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 61):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 62):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 63):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 64):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 66):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 68):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 69):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 70):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 71):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 73):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 80):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 81):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 82):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 83):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 85):
## 
##     tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 88):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 89):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 90):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following objects are masked from base (pos = 91):
## 
##     marca, tecnico, tiempo</code></pre>
<pre><code>## The following object is masked from ensamble (pos = 93):
## 
##     tiempo</code></pre>
<pre><code>## Efectos Técnico*Marca sobre respuesta Tiempo particionados por
## Marca</code></pre>
<pre><code>##           Df   Sum Sq  Mean Sq       F0     P.Value
## En Marca1  2 448.9333 224.4667 4.315744 0.020888163
## En Marca2  2 581.2000 290.6000 5.587268 0.007703847
## En Marca3  2 209.7333 104.8667 2.016236 0.147918236</code></pre>
<pre><code>## Efectos Técnico*Marca sobre respuesta Tiempo particionados por
## Técnico</code></pre>
<pre><code>##             Df   Sum Sq  Mean Sq       F0    P.Value
## En Técnico1  2 430.5333 215.2667 4.138859 0.02410520
## En Técnico2  2 416.1333 208.0667 4.000427 0.02698640
## En Técnico3  2 396.9333 198.4667 3.815851 0.03140553</code></pre>
<pre><code>##             Df   Sum Sq  Mean Sq       F0    P.Value
## En Técnico1  2 430.5333 215.2667 4.138859 0.02410520
## En Técnico2  2 416.1333 208.0667 4.000427 0.02698640
## En Técnico3  2 396.9333 198.4667 3.815851 0.03140553</code></pre>
<ol start="8" style="list-style-type: decimal">
<li>Valide supuestos sobre los errores del modelo (varianza cte. y normalidad)</li>
</ol>
<pre class="r"><code>shapiro.test(residuals(model))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(model)
## W = 0.96922, p-value = 0.2712</code></pre>
<pre class="r"><code>nf=layout(rbind(c(1,1,2,2),c(3,3,4,4)))

plot(fitted(model),rstudent(model),cex=2,main=&quot;Residuales estudentizados vs. valores ajustados&quot;,xlab=&quot;Valores ajustados&quot;)
abline(h=c(-2,0,2),col=2)

plot(as.numeric(marca),rstudent(model),main=&quot;Residuales estudentizados vs. marca&quot;,xlab=&quot;marca&quot;)
abline(h=c(-2,0,2),col=2)

plot(as.numeric(tecnico),rstudent(model),cex=2, main=&quot;Residuales estudentizados vs. técnico&quot;,xlab=&quot;técnico&quot;)
abline(h=c(-2,0,2),col=2)

qqnorm(residuals(model),cex=2)
qqline(residuals(model),col=2)</code></pre>
<p><img src="diseñofactorial_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>plot(model)</code></pre>
<p><img src="diseñofactorial_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<p><strong>Código gerneral</strong></p>
<pre class="r"><code>##Análisis descriptivo de los datos
tecnico=factor(rep(c(1,2,3),each=5,times=3))
marca=factor(c(rep(1,15),rep(2,15),rep(3,15)))
tiempo=c(62,48,63,57,69,51,57,45,50,39,59,65,55,52,70,57,45,39,54,44,61,58,70,66,51,58,63,70,   53,60,59,53,67,66,47,55,58,50,69,49,47,56,51,44,50)

base=data.frame(marca,tecnico,tiempo)  
attach(base)

##Medias por tratamiento
mediastécnico=sapply(split(tiempo,tecnico),mean)
mediasmarca=sapply(split(tiempo,marca),mean)

##graficos
##Gráficos de interacción
par(mfrow=c(1,2))
interaction.plot(tecnico,marca,tiempo,type=&quot;b&quot;,pch=c(1,2,3),col=c(&quot;black&quot;,&quot;blue&quot;,&quot;red&quot;),lwd=2)
interaction.plot(marca,tecnico,tiempo,type=&quot;b&quot;,pch=c(1,2,3),col=c(&quot;black&quot;,&quot;blue&quot;,&quot;red&quot;),lwd=2)

##Gráficos boxplot
boxplot(tiempo~tecnico)
boxplot(tiempo~marca)

##medias por combinación de tratamiento
aggregate(tiempo ~ marca+tecnico, FUN = mean)


#modelo de análisis de varianza 

model=aov(tiempo~marca*tecnico)

summary(model)


#iNTERVALOS tukey de medias

TukeyHSD(model,&quot;marca:tecnico&quot;,conf.level=0.95)

plot(TukeyHSD(model,conf.level = 0.95))

##cOMPARACIÓN DE MEDIAS POR CADANIVELDE TRATAMIENTO


tecnico=factor(rep(c(1,2,3),each=5,times=3))
marca=factor(c(rep(1,15),rep(2,15),rep(3,15)))
tiempo=c(62,48,63,57,69,51,57,45,50,39,59,65,55,52,70,57,45,39,54,44,61,58,70,66,51,58,63,70,53,60,59,53,67,66,47,55,58,50,69,49,47,56,51,44,50)

base=data.frame(marca,tecnico,tiempo)  
attach(base)

model=aov(tiempo~marca*tecnico)

MSE=anova(model)[3][4,]
dftecnico=length(levels(tecnico))-1
dfmarca=length(levels(marca))-1
dferror=anova(model)[1][4,]

# Anova del factor técnico en cada nivel de marca
Técnicos.marca1=anova(aov(tiempo~tecnico,data=base[marca==1,]))
Técnicos.marca2=anova(aov(tiempo~tecnico,data=base[marca==2,]))
Técnicos.marca3=anova(aov(tiempo~tecnico,data=base[marca==3,]))


Comp_técnicos_en_marca=rbind(&quot;En Marca1&quot;=Técnicos.marca1[1:3][1,],
&quot;En Marca2&quot;=Técnicos.marca2[1:3][1,],&quot;En Marca3&quot;=Técnicos.marca3[1:3][1,])

F0_técnicos=data.frame(Comp_técnicos_en_marca[3]/MSE)
names(F0_técnicos)[1]=&quot;F0&quot;

pv=data.frame(&quot;P.Value&quot;=pf(F0_técnicos[,1],dftecnico,dferror,lower.tail=F))

Slice_técnicos_por_marca=cbind(Comp_técnicos_en_marca,F0_técnicos,pv)
cat(&quot;Efectos Técnico*Marca sobre respuesta Tiempo particionados por
Marca&quot;,&quot;\n&quot;)

Slice_técnicos_por_marca


#Anova del factor marca en cada nivel de tecnico

marcas.tec1=anova(aov(tiempo~marca,data=base[tecnico==1,]))
marcas.tec2=anova(aov(tiempo~marca,data=base[tecnico==2,]))
marcas.tec3=anova(aov(tiempo~marca,data=base[tecnico==3,]))


Comp_marcas_en_Tec=rbind(&quot;En Técnico1&quot;=marcas.tec1[1:3][1,],
&quot;En Técnico2&quot;=marcas.tec2[1:3][1,],&quot;En Técnico3&quot;=marcas.tec3[1:3][1,])


F0_marcas=data.frame(Comp_marcas_en_Tec[3]/MSE)
names(F0_marcas)[1]=&quot;F0&quot;

pv=data.frame(&quot;P.Value&quot;=pf(F0_marcas[,1],dfmarca,dferror,lower.tail=F))

Slice_marcas_por_Técnico=cbind(Comp_marcas_en_Tec,F0_marcas,pv)
cat(&quot;Efectos Técnico*Marca sobre respuesta Tiempo particionados por
Técnico&quot;,&quot;\n&quot;);Slice_marcas_por_Técnico


Slice_marcas_por_Técnico</code></pre>
<p><strong>Ejemplo de un diseño con tres factores de efectos fijos </strong></p>
</div>

<br>
<hr>
<p><center>Copyright &copy; 2019, webpage made with Rmarkdown.</center></p>
<hr>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
