<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>DISEÑO EN BLOQUE</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link href="site_libs/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" />
<link rel="icon" type="image/png" href="images/favicon.png" />

<script type="text/javascript" src="js/rmarkdown.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-88209726-1', 'auto');
  ga('send', 'pageview');
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Estadística ITM</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="pagin1.html">
    <span class="fas fa-line-chart"></span>
     
    Estadística Básica
  </a>
</li>
<li>
  <a href="pagin2.html">
    <span class="fas fa-bar-chart-o"></span>
     
    Estadística inferencial
  </a>
</li>
<li>
  <a href="pagin3.html">
    <span class="fas fa-pie-chart"></span>
     
    Análisis multivariado
  </a>
</li>
<li>
  <a href="about.html">
    <span class="fas fa-puzzle-piece"></span>
     
    Semillero de R
  </a>
</li>
<li>
  <a href="https://www.itm.edu.co">
    <span class="ion ion-university"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/estadisticaITM">
    <span class="fas fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">DISEÑO EN BLOQUE</h1>

</div>


<ul>
<li><p>Un experimento puede involucrar uno o más factores con efecto sobre la respuesta.</p></li>
<li><p>Compara los efectos de diferentes tratamientos y bloques, aplicados a las unidades experimentales sobre condiciones diferentes.</p></li>
<li><p>Las unidades experimentales son agrupadas en conjuntos de tal forma que dos unidades experimentales en el mismo grupo son similares y pueden ser medidas bajo condiciones experimentales similares.</p></li>
<li><p>Los grupos de unidades experimentales similares son llamados bloques.</p></li>
<li><p>Las condiciones que varían de bloque a bloque forman los niveles del factor de bloqueo.</p></li>
<li><p>El propósito de bloquear es prevenir que diferencias grandes en las unidades experimentales enmascaren las diferencias entre los niveles del factor de tratamiento.</p></li>
<li><p>Permite que los tratamientos sean examinados bajo diferentes condiciones experimentales.</p></li>
<li><p>Los niveles de un factor de bloqueo son agrupamientos de características que no pueden ser medidas convenientemente.</p></li>
</ul>
<p>##Ejemplo</p>
<ul>
<li><p>Los experimentadores agrícolas pueden saber que parcelas cercanas en un campo son similares, en tanto que las parcelas lejanas no lo son.</p></li>
<li><p>Los experimentadores industriales pueden saber que dos unidades producidas por una misma máquina tienen características similares, mientras que aquellas producidas por dos máquinas distintas son algo diferentes.</p></li>
<li><p>Los experimentadores clínicos pueden saber que las mediciones tomadas sobre el mismo sujeto serán similares, mientras que aquellas tomadas sobre sujetos distintos no lo serán.</p></li>
</ul>
<p>##<strong>ASPECTOS DEL DISEÑO EN BLOQUE</strong></p>
<ul>
<li><p>Considere b bloques, de tamaño k</p></li>
<li><p>a niveles del factor de estudio</p></li>
<li><p>Una vez determinado el número de bloques y se hayan agrupado a las unidades experimentales en tales grupos, a continuación se asignan las unidades a los tratamientos.</p></li>
<li><p>La mejor asignación a cada tratamiento es distribuir el mismo número de unidades experimentales en cada bloque.</p></li>
<li><p>Si el tamaño del bloque k es múltiplo del número de niveles o tratamientos del factor, el diseño recibe el nombre de ** bloques completos**</p></li>
<li><p>Si el tamaño de bloque no es múltiplo de a, entonces el diseño es conocido como un diseño de <strong>bloques incompletos</strong></p></li>
</ul>
<div id="ejemplo" class="section level2">
<h2>Ejemplo</h2>
<p>Se realiza un estudio para comprobar la efectividad en el retraso del crecimiento de bacterias utilizando cuatro soluciones diferentes para lavar los envases de la leche. El análisis se realiza en el laboratorio y sólo se pueden realizar seis pruebas en un mismo día. Como los días son una fuente de variabilidad potencial, el investigador decide utilizar un diseño aleatorizado por bloques, pero al recopilar las observaciones durante seis días no ha sido posible aplicar todos los tratamientos en cada día, sino que sólo se han podido aplicar dos de las cuatro soluciones cada día. Se decide utilizar un diseño en bloques incompletos balanceado.</p>
<table>
<thead>
<tr class="header">
<th></th>
<th>dias</th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Soluciones</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
</tr>
<tr class="even">
<td>solución 1</td>
<td>12</td>
<td>24</td>
<td>31</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>solución 2</td>
<td>21</td>
<td></td>
<td></td>
<td></td>
<td>20</td>
<td>21</td>
</tr>
<tr class="even">
<td>solución 3</td>
<td></td>
<td></td>
<td>19</td>
<td>18</td>
<td></td>
<td>19</td>
</tr>
<tr class="odd">
<td>solución 4</td>
<td></td>
<td>15</td>
<td></td>
<td>19</td>
<td>47</td>
<td></td>
</tr>
</tbody>
</table>
<p>En este experimento se tienen b=6 bloques que son los dias, de tamaño k=2, mientras que los tratamientos a=4, corresponden a las 4 soluciones</p>
<p>##<strong>Diseño en bloques completos al azar</strong></p>
<ul>
<li><p>Este diseño con a tratamientos y con N=ab unidades experimentales agrupadas en b bloques.</p></li>
<li><p>las unidades dentro de un bloque son similares y unidades en bloques diferentes son sustancialmente distintas.</p></li>
<li><p>Las unidades experimentales en cada bloque son asignadas aleatoriamente a los a tratamientos de modo que cada tratamiento es asignado a una unidad por bloque.</p></li>
<li><p>Una tabla de entrada de datos para este modelo es:</p></li>
</ul>
<table>
<colgroup>
<col width="18%" />
<col width="16%" />
<col width="16%" />
<col width="3%" />
<col width="8%" />
<col width="3%" />
<col width="8%" />
<col width="24%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Bloques</th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tratamientos</td>
<td>1</td>
<td>2</td>
<td>…</td>
<td>j</td>
<td>…</td>
<td>b</td>
<td>Medias de tratamientos</td>
</tr>
<tr class="even">
<td>1</td>
<td><span class="math inline">\(Y_{11}\)</span></td>
<td><span class="math inline">\(Y_{12}\)</span></td>
<td>…</td>
<td><span class="math inline">\(Y_{1j}\)</span></td>
<td>…</td>
<td><span class="math inline">\(Y_{1b}\)</span></td>
<td><span class="math inline">\(\bar{Y_{1\bullet}}\)</span></td>
</tr>
<tr class="odd">
<td>2</td>
<td><span class="math inline">\(Y_{21}\)</span></td>
<td><span class="math inline">\(Y_{22}\)</span></td>
<td>…</td>
<td><span class="math inline">\(Y_{2j}\)</span></td>
<td>…</td>
<td><span class="math inline">\(Y_{2b}\)</span></td>
<td><span class="math inline">\(\bar{Y_{2\bullet}}\)</span></td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>i</td>
<td><span class="math inline">\(Y_{i1}\)</span></td>
<td><span class="math inline">\(Y_{i2}\)</span></td>
<td>..</td>
<td><span class="math inline">\(Y_{ij}\)</span></td>
<td>…</td>
<td><span class="math inline">\(Y_{ib}\)</span></td>
<td><span class="math inline">\(\bar{Y_{i\bullet}}\)</span></td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>a</td>
<td><span class="math inline">\(Y_{a1}\)</span></td>
<td><span class="math inline">\(Y_{a2}\)</span></td>
<td>..</td>
<td><span class="math inline">\(Y_{aj}\)</span></td>
<td>…</td>
<td><span class="math inline">\(Y_{ab}\)</span></td>
<td><span class="math inline">\(\bar{Y_{a\bullet}}\)</span></td>
</tr>
<tr class="even">
<td>Medias de bloques</td>
<td><span class="math inline">\(Y_{\bullet 1}\)</span></td>
<td><span class="math inline">\(Y_{\bullet 2}\)</span></td>
<td>..</td>
<td><span class="math inline">\(Y_{\bullet j}\)</span></td>
<td>…</td>
<td><span class="math inline">\(Y_{\bullet i}\)</span></td>
<td>Media global <span class="math inline">\(\bar{Y_{\bullet \bullet}}\)</span></td>
</tr>
</tbody>
</table>
<p>##<strong>Modelo ANOVA</strong></p>
<p><span class="math display">\[\Large Y_{ij}=\mu+\alpha_i+\beta_j+\varepsilon_{ij}\]</span></p>
<p>Donde</p>
<ul>
<li><p><span class="math inline">\(\large Y_{ij}\)</span> es la Variable aleatoria que representala medición del bloque j, del tratamiento i.</p></li>
<li><p><span class="math inline">\(\large \mu\)</span> denota la respuesta global promedio</p></li>
<li><p><span class="math inline">\(\large \alpha\)</span> es el efecto del i-ésimo tratamiento sobre el promedio global</p></li>
</ul>
<p>-<span class="math inline">\(\large \beta_j\)</span> es el efecto del j-ésimo bloque</p>
<p>Este modelo asume que no existe interacción entre el factor de interés y el factor de bloqueo; en muchas situaciones esta presunción será razonable, sin embargo, si se sospecha que hay interacción, el tamaño del bloque deberá ser incrementado para permitir estimar estos efectos.</p>
<p>Los niveles del factor de bloque representan agrupamientos intencionales de las unidades experimentales, mientras que los tratamientos son asignados de manera aleatoria a las unidades experimentales.</p>
<p>El interés no está centrado en las medias de los bloques, si no en la suma de cuadrados medios debida al factor de bloqueo con el MSE del modelo, para determinar si bloquear fue o no benéfico en el experimento.</p>
<table>
<colgroup>
<col width="17%" />
<col width="19%" />
<col width="18%" />
<col width="18%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th>Fuente de variación</th>
<th>Grados de libertad</th>
<th>Suma de cuadrados</th>
<th>cuadrados medios</th>
<th>Valores esperados</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Factor A</td>
<td>a-1</td>
<td>SSA</td>
<td><span class="math inline">\(MSA=SSA/(a-1)\)</span></td>
<td><span class="math inline">\(\Large E(MSA)=\sigma^2+ \frac{\sum_{i=1}^n\alpha_i^2}{a-1}\)</span></td>
</tr>
<tr class="even">
<td>Bloque</td>
<td>b-1</td>
<td>SSB</td>
<td><span class="math inline">\(MSB=SSB/(b-1)\)</span></td>
<td><span class="math inline">\(\Large E(MSB)=\sigma^2+ \frac{\sum_{i=1}^n\beta_i^2}{a-1}\)</span></td>
</tr>
<tr class="odd">
<td>Error</td>
<td>(a-1)(b-1)</td>
<td>SSE</td>
<td><span class="math inline">\(MSE=SSE/(a-1)(b-1)\)</span></td>
<td><span class="math inline">\(E(MSE)=\sigma^2\)</span></td>
</tr>
<tr class="even">
<td>Total</td>
<td>ab-1</td>
<td>SST</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Fórmulas</strong></p>
<p>Las sumas de cuadrados del modelo ANOVA SST=SSA+SSB+SSE</p>
<p><span class="math display">\[\Large SST=\sum_{i=1}^a \sum_{j=1}^{b}(Y_{ij}-\bar{Y}_{\bullet \bullet})^2=\sum_{i=1}^a \sum_{j=1}^{n_i} Y^2_{ij}-ab\bar{Y}_{\bullet \bullet}^2 \]</span></p>
<p>-La variabilidad en la respuesta explicada por el factor A, con a -1 grados de libertad, está dada por:</p>
<p><span class="math display">\[\Large SSA=\sum_{i=1}^a \sum_{j=1}^{b}(Y_{i\bullet}-\bar{Y}_{\bullet \bullet})^2=b\sum_{i=1}^a \bar{Y^2_{i\bullet}}-ab\bar{Y}_{\bullet \bullet}^2 \]</span></p>
<p>-La variabilidad en la respuesta explicada por el bloque B, con b-1 grados de libertad, está dada por:</p>
<p><span class="math display">\[\Large SSB=\sum_{i=1}^a \sum_{j=1}^{b}(Y_{\bullet j}-\bar{Y}_{\bullet \bullet})^2=a\sum_{i=1}^a \bar{Y^2_{\bullet j}}-ab\bar{Y}_{\bullet \bullet}^2 \]</span></p>
<ul>
<li>La variabilidad en la respuesta explicada por la aleatoriedad, con (a-1)(b-1) grados de libertad, está dada por</li>
</ul>
<p><span class="math display">\[\Large SSE=SST-SSA-SSB\]</span></p>
<p>La media muestral en el nivel i del factor de tratamiento está dada por: <span class="math display">\[\Large \hat {\mu}_i=\bar{Y}_{i \bullet}=\frac{1}{b} \sum_{j=1}^b Y_{ij}\]</span></p>
<p>La media muestral en el nivel j del bloque está dada por:</p>
<p><span class="math display">\[\Large \hat {\mu}_j=\bar{Y}_{ \bullet j }=\frac{1}{a} \sum_{j=1}^a Y_{ij}\]</span></p>
<p><strong>Hipótesis de interés</strong></p>
<p>La prueba de hipótesis asociada al ANOVA esta dado por:</p>
<p><span class="math inline">\(\Large H_0=\mu_1=\mu_2=...=\mu_i\)</span></p>
<p><span class="math inline">\(\Large H_1= \mu_1\not=\mu_2 \not =...\not =\mu_i\)</span></p>
<p><strong>Notas de interés</strong></p>
<ul>
<li><p>Si el MSB es considerablemente mayor que el MSE, esto sugiere que la creación de bloques valió la pena en el sentido de que sirvió para reducir el tamaño del error experimental.</p></li>
<li><p>Recuerde que no hay conclusión estadística acerca de la igualdad de medias de bloques o de significancia de efectos de bloques; la comparación se hace como una forma de establecer la utilidad de haber creado bloques en el experimento, proporciona información para la planeación futura de experimentos similares.</p></li>
<li><p>También se realiza la prueba de contrastes entre medias por medio de la prueba de intervalos tukey</p></li>
<li><p>se verifica independencia, normalidad y varianza constante en los residuales</p></li>
</ul>
</div>
<div id="ejemplo-1" class="section level2">
<h2><strong>Ejemplo</strong></h2>
<p>Un equipo de mejora investiga el efecto de cuatro métodos de ensamble A, B, C, y D, sobre el tiempo de ensamble en minutos. En primera instancia la estrategia experimental fue aplicar cuatro veces los cuatro métodos de ensamble en orden aleatorio en un diseño completamente aleatorizado. Sin embargo, los experimentadores se dan cuenta que hay cuatro operadores con distintas destrezas y consideran que esto puede afectar de manera significativa los tiempos de ensamble, y por ende la comparación de los métodos, entonces debe utilizarse un diseño de bloques completos aleatorizados para controlar activamente en el experimento a los operadores que realizarán el ensamble. Los datos recolectados en este diseño fueron los siguientes:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th>Método</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Operadores</td>
<td>A</td>
<td>B</td>
<td>C</td>
<td>D</td>
</tr>
<tr class="even">
<td>1</td>
<td>6</td>
<td>7</td>
<td>10</td>
<td>10</td>
</tr>
<tr class="odd">
<td>2</td>
<td>9</td>
<td>10</td>
<td>16</td>
<td>13</td>
</tr>
<tr class="even">
<td>3</td>
<td>7</td>
<td>11</td>
<td>11</td>
<td>11</td>
</tr>
<tr class="odd">
<td>4</td>
<td>8</td>
<td>8</td>
<td>14</td>
<td>9</td>
</tr>
</tbody>
</table>
<p>Se desea determinar si existen diferencias entre los cuatro métodos y cómo se diferencian, además elegir el mejor método, si lo hay.</p>
<ol style="list-style-type: lower-alpha">
<li>Analice los datos experimentales</li>
</ol>
<p><img src="diseñobloque_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Especifique el modelo para este experimento.</li>
</ol>
<p>El modelo estadístico es:</p>
<p><span class="math display">\[\Large Y_{ij}=\mu+\alpha_i+\beta_j+\varepsilon_{ij}\]</span></p>
<p>con i=1,2,3,4 para denotar los métodos A,B,C,D y j=1,2,3,4 para los operadores</p>
<p>Donde</p>
<ul>
<li><p><span class="math inline">\(\large Y_{ij}\)</span> es la Variable aleatoria que representala medición del bloque j, del tratamiento i.</p></li>
<li><p><span class="math inline">\(\large \mu\)</span> denota el tiempo promedio global</p></li>
<li><p><span class="math inline">\(\large \alpha\)</span> es el efecto del i-ésimo método sobre el tiempo de ensamble.</p></li>
<li><p><span class="math inline">\(\large \beta_j\)</span> es el efecto del j-ésimo operador sobre el tiempo de ensamble</p></li>
</ul>
<p>Bajo los puestos de que</p>
<p><span class="math display">\[\large \sum_{i=1}^4\alpha_i=\sum_{j=1}^4\beta_j=0\]</span> Además <span class="math display">\[\Large \varepsilon_{ij} \sim N(0,\sigma^2)\]</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Construya la tabla ANOVA y asumiendo válidos los supuestos del modelo, haga las pruebas de hipótesis pertinentes.</li>
</ol>
<p>ANOVA:</p>
<pre class="r"><code>library(gmodels)
library(multcomp)</code></pre>
<pre><code>## Warning: package &#39;multcomp&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Loading required package: mvtnorm</code></pre>
<pre><code>## Loading required package: survival</code></pre>
<pre><code>## Loading required package: TH.data</code></pre>
<pre><code>## Loading required package: MASS</code></pre>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<pre><code>## The following object is masked from &#39;package:plotly&#39;:
## 
##     select</code></pre>
<pre><code>## 
## Attaching package: &#39;TH.data&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:MASS&#39;:
## 
##     geyser</code></pre>
<pre class="r"><code>método=factor(rep(c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;),4))
operador=factor(c(rep(1,4),rep(2,4),rep(3,4),rep(4,4)))
tiempo=c(6,7,10,10,9,10,16,13,7,11,11,11,8,8,14,9)
ensamble=data.frame(método,operador,tiempo)



#Anova
diseño=aov(tiempo~método+operador)
anova(diseño)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: tiempo
##           Df Sum Sq Mean Sq F value   Pr(&gt;F)   
## método     3   61.5    20.5   10.25 0.002919 **
## operador   3   28.5     9.5    4.75 0.029846 * 
## Residuals  9   18.0     2.0                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><span class="math inline">\(\Large H_0= \alpha_a=\alpha_b=\alpha_c=\alpha_D\)</span></p>
<p><span class="math inline">\(\Large H_1= Algun \quad par \quad \alpha_i\not= \alpha_j\)</span></p>
<p>El test de hipótesis es rechazado con un valor p de 0.0029 a un nivel de significancia de 0.05, es decir, los tiempos medios de ensamble no son iguales para todos los métodos.</p>
<p>Para evaluar la eficiencia del diseño tenemos que la seudo – prueba sobre los efectos de bloque (operador) tiene un <span class="math inline">\(F_0=4.75\)</span> y un valor p: <span class="math inline">\(P(f_{3.9&gt;4.75})=0.0298\)</span>, que nos indica el bloqueo por operario resultó útil o eficiente para reducir el error experimental y por tanto un ahorro en cuanto al número de réplicas necesarias para detección de diferencias entre los métodos.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Asumiendo válidos los supuestos del modelo, compare las medias de tratamiento mediante Tukey. De acuerdo a los resultados, responda a las dos cuestiones planteadas en la investigación.</li>
</ol>
<pre class="r"><code>library(gmodels)
library(multcomp)




método=factor(rep(c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;),4))
operador=factor(c(rep(1,4),rep(2,4),rep(3,4),rep(4,4)))
tiempo=c(6,7,10,10,9,10,16,13,7,11,11,11,8,8,14,9)
ensamble=data.frame(método,operador,tiempo)

TukeyHSD(diseño,&quot;método&quot;,conf.level=0.95)</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = tiempo ~ método + operador)
## 
## $método
##      diff        lwr      upr     p adj
## B-A  1.50 -1.6217987 4.621799 0.4758801
## C-A  5.25  2.1282013 8.371799 0.0024211
## D-A  3.25  0.1282013 6.371799 0.0412298
## C-B  3.75  0.6282013 6.871799 0.0195634
## D-B  1.75 -1.3717987 4.871799 0.3548246
## D-C -2.00 -5.1217987 1.121799 0.2566550</code></pre>
<pre class="r"><code>plot(TukeyHSD(diseño,&quot;método&quot;,conf.level = 0.95),cex.lab=0.8,las=1)</code></pre>
<p><img src="diseñobloque_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>La prueba de hipótesis de interés es:</p>
<p><span class="math inline">\(\Large H_o=\mu_i=\mu_j\)</span></p>
<p><span class="math inline">\(\Large H_1=\mu_i\not=\mu_j\)</span></p>
<p>Como vemos Tukey define tres grupos de medias que se traslapan:</p>
<p>grupo 1: métodos C y D grupo 2: métodos D y B<br />
grupo 3: métodos A y B.</p>
<p>Hay un problema de potencia del procedimiento debido a la gran dispersión en los datos en algunos operarios y métodos como veremos.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Estime los efectos de cada metodo sobre el tiempo de ensamble. Dé tanto la estimación puntual como los intervalos de confianza individuales del 95%.</li>
</ol>
<pre class="r"><code>library(gmodels)
library(multcomp)

método=factor(rep(c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;),4))
operador=factor(c(rep(1,4),rep(2,4),rep(3,4),rep(4,4)))
tiempo=c(6,7,10,10,9,10,16,13,7,11,11,11,8,8,14,9)
ensamble=data.frame(método,operador,tiempo)
attach(ensamble)</code></pre>
<pre><code>## The following objects are masked _by_ .GlobalEnv:
## 
##     método, operador, tiempo</code></pre>
<pre class="r"><code>#medias dE tratamientos con sus INTERVALOS
##divide el marco de datos por método
met=split(ensamble,método)

##Método A
metA=met$A
t.test(metA$tiempo,conf.level = 0.95)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  metA$tiempo
## t = 11.619, df = 3, p-value = 0.001369
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  5.44574 9.55426
## sample estimates:
## mean of x 
##       7.5</code></pre>
<pre class="r"><code>##Método B
metB=met$B
t.test(metB$tiempo,conf.level = 0.95)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  metB$tiempo
## t = 9.859, df = 3, p-value = 0.002219
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##   6.094837 11.905163
## sample estimates:
## mean of x 
##         9</code></pre>
<pre class="r"><code>##Método C
metC=met$C
t.test(metC$tiempo,conf.level = 0.95)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  metC$tiempo
## t = 9.26, df = 3, p-value = 0.002665
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##   8.368113 17.131887
## sample estimates:
## mean of x 
##     12.75</code></pre>
<pre class="r"><code>##Método D
metD=met$D
t.test(metD$tiempo,conf.level = 0.95)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  metD$tiempo
## t = 12.589, df = 3, p-value = 0.001081
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##   8.032469 13.467531
## sample estimates:
## mean of x 
##     10.75</code></pre>
<ol start="6" style="list-style-type: lower-alpha">
<li>Valide supuestos. Use gráficos de residuales estudentizados y test de Levene para evaluar varianza constante. Use Shapiro Wilk para probar supuestos de normalidad. Diagnostique observaciones atípicas. ¿Qué repercusiones pueden tener los resultados de estas validaciones sobre el modelo y las inferencias realizadas en los literales anteriores?</li>
</ol>
<pre class="r"><code>library(gmodels)
library(multcomp)

método=factor(rep(c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;),4))
operador=factor(c(rep(1,4),rep(2,4),rep(3,4),rep(4,4)))
tiempo=c(6,7,10,10,9,10,16,13,7,11,11,11,8,8,14,9)
ensamble=data.frame(método,operador,tiempo)
diseño=aov(tiempo~método+operador)

par(mfrow=c(2,2))

plot(diseño)</code></pre>
<p><img src="diseñobloque_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>residuales=residuals(diseño)
shapiro.test(residuales)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuales
## W = 0.97299, p-value = 0.8844</code></pre>
<pre class="r"><code>bartlett.test(tiempo ~ método )</code></pre>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  tiempo by método
## Bartlett&#39;s K-squared = 1.5989, df = 3, p-value = 0.6596</code></pre>
<p>Validemos ahora los supuestos de normalidad y de varianza constante mediante gráficos de residuales: La normalidad parece un supuesto razonable para los errores en este experimento. Sin embargo, hay problemas con el supuesto de varianza constante. Con los métodos B y C la dispersión de los residuales es mayor comparativamente a la dispersión en los métodos A y D. Con el método A hay menos dispersión. A nivel del operador 3 la dispersión de los residuales es mayor aparentemente debido a una observación que es subestimada. A pesar de estos inconvenientes es posible llegar a una conclusión: “Elegir como mejor método el A, dado que tiene menor tiempo promedio observado y menor dispersión” (esto último indica que los operadores con este método son más consistentes)</p>
<p>Prueba de normalidad <span class="math inline">\(\Large H_o=\)</span> Los residuos son normales <span class="math inline">\(\Large H_o=\)</span> Los residuos no son normales</p>
<p>Prueba de barlett para homogeneidad de varianzas</p>
<p><span class="math inline">\(\Large H_0=\sigma_A^2=\sigma_B^2=...=\sigma_D^2\)</span></p>
<p><span class="math inline">\(\Large H_1= \sigma_A^2\not=\sigma_B^2 \not =...\not =\sigma_D^2\)</span></p>
</div>

<br>
<hr>
<p><center>Copyright &copy; 2019, webpage made with Rmarkdown.</center></p>
<hr>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
