---
title: "gama"
---

La distribución gama estándar tiene β= 1, así que la función de densidad de probabilidad de una variable aleatoria gama estándar es:

$$f(x)=\left\{ \begin{array}{lc}
            \\ 0 &   si  & x < 0 \\
             \\ \frac{x^{\alpha-1}e^{-x}}{\Gamma (\alpha)} &  si  & x \geq 0 
             \end{array}
   \right.$$



La distribución exponencial se deriva de considerar   α=1 y  β=1/λ

La media y la varianza de una variable aleatoria X que tiene la distribución gama f (x, α,β) son:

$$E(x)=μ=αβ$$

$$V(x)=αβ^2$$

Si X tiene una distribución gama con parámetros α y β, luego la función de distribución acumulativa de X es:
$$P(X≤x)=F(x;α,β)=F(\frac{x}{β};α)$$
**Ejemplo:**

Suponga que el tiempo de reacción X de un individuo seleccionado al azar a un estímulo tiene una distribución gama estándar con α=2.  Como  X es continua:
𝑷(𝒂≤𝒙≤𝒃)=𝑭(𝒃)−𝑭(𝒂)
𝑷(3≤𝒙≤5)=𝑭(x=5,α=2)−𝑭(x=3,α=2)
= 0.960 - 0.801 = 0.159
La probabilidad de que el tiempo de reacción sea de más de 4 s es
P(x>4)=1-P(x≤4)
=1-F(x=4,α=2)
=1-0.908=0.092

**Ejercicios**
1.  Suponga que cuando un transistor de cierto tipo se somete a una prueba de duración acelerada, la duración X (en semanas) tiene una distribución gama acelerada con media de 24 semanas y desviación estándar de 12 semanas.
a. Halle el valor de α y β
b. Cuál es la probabilidad de que un transistor dure entre 18 y 24 semanas? 
c. ¿Cuál es la probabilidad de que un transistor dure cuando mucho 36 semanas?

2. En cierta ciudad el consumo diario de energía eléctrica, en millones de kilovatios por hora, puede considerarse como una variable aleatoria con distribución gama de parámetros α= 3 y β=2. La planta de energía de esta ciudad tiene una capacidad diaria de 10 millones de KW/hora ¿Cuál es la probabilidad de que este abastecimientos sea: 
2.1. Insuficiente en un día cualquiera? 
2.2 Se consuman entre 3 y 8 millones de K. W./Hora? 
2.3 Encuentre E(x) y V(x)

