
---
title: "ESTADÍSTICA INFERENCIAL"
---


```{r fig.asp=0.6, fig.align='center', echo=FALSE}

library(png)
library(grid)
img2 <- readPNG("infff.png")
grid.raster(img2)

```



## Documentos de interés


[Día a Día ](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/DIA-%20DIA_XREI03__ESTADISTICA%20INFERENCIAL_2022-1%20(1).pdf)

## **Unidades temáticas**


### Repaso de estadística descriptiva

<a href="descriptiva2.html" target="_blank"> Conceptos de estadística descriptiva</a>

### Distribución normal

<a href="normal.html" target="_blank"> Distribución normal</a>


### Muestreo

<a href="muestreo.html" target="_blank"> Muestreo</a>

### Teorema de límite central y distribuciones de muestreo

- [Aplicativo distribuciones de muestreo](https://amgq828.shinyapps.io/distri/)


- [Distribuciones asociadas al muestreo](https://github.com/jtrochezg/jtrochezg.github.io/blob/master/sampling-distributions1.pdf)


- <a href="tlc.html" target="_blank"> Teorema de límite central y las distribuciones de muestreo</a>

- <a href="tdm.html" target="_blank"> Taller distribuciones de muestreo</a>

Bibliografía 

- https://virtual.uptc.edu.co/ova/estadistica/docs/libros/estadistica1/toc.html

- https://www.aulaclic.es/estadistica-excel/index.htm 

### Estimación puntual
<a href="estima.html" target="_blank"> Estimación puntual y sus propiedades</a>

### Intervalos de confianza

<a href="IC.html" target="_blank"> Intervalos de confianza</a>

### Pruebas de hipótesis

<a href="PH.html" target="_blank"> Pruebas de hipótesis</a>

Taller de tamaños de muestra, intervalos de confianza y pruebas de hipótesis 

[Tamaños de muestra, intervalos de confianza, PH](https://github.com/estadisticaITM/repositorioprueba/blob/master/Taller%20de%20tama%C3%B1os%20de%20muestra%2C%20intervalos%20de%20confianza%20y%20ph.pdf)

### Pruebas Pruebas no paramétricas 
<a href="pruebas-no-paramétricas.html" target="_blank"> Clase de pruebas no paramétricas</a>

### Regresión lineal 
<a href="regrelineal.html" target="_blank"> Clase de regresión</a>

### Diseño de experimentos 
<a href="pagin2.html" target="_blank"> Clase de diseño experimentos</a>

### Analisis multivariado 
<a href="pagin3.html" target="_blank"> Análisis multivariado</a>

### Tablas de diferentes distribuciones de probabilidad


[Aqui](https://github.com/estadisticaITM/repositorioprueba/blob/master/tabla%20de%20diferentes%20probabilidades.pdf)

**Fórmulas**

[Fórmulas](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/f%C3%B3rmulas.pdf)

### Trabajo final

<a href="posterestdesc1.html" target="_blank"> Pautas para el trabajo final</a>


