<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Introducción</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="site_libs/viz-1.8.2/viz.js"></script>
<link href="site_libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="site_libs/grViz-binding-1.0.11/grViz.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link href="site_libs/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" />
<link rel="icon" type="image/png" href="images/favicon.png" />

<script type="text/javascript" src="js/rmarkdown.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-88209726-1', 'auto');
  ga('send', 'pageview');
</script>


<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Estadística ITM</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="pagin1.html">
    <span class="fa fa-line-chart"></span>
     
    Est Básica
  </a>
</li>
<li>
  <a href="inf.html">
    <span class="fa fa-bar-chart-o"></span>
     
    Est inferencial
  </a>
</li>
<li>
  <a href="pagin2.html">
    <span class="fa fa-bar-chart-o"></span>
     
    Diseño de exp
  </a>
</li>
<li>
  <a href="pagin3.html">
    <span class="fa fa-pie-chart"></span>
     
    Análisis multivariado
  </a>
</li>
<li>
  <a href="medi.html">
    <span class="fa fa-puzzle-piece"></span>
     
    Medición
  </a>
</li>
<li>
  <a href="https://www.itm.edu.co">
    <span class="ion ion-university"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/estadisticaITM">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Introducción</h1>

</div>


<div id="estadística-y-metrología" class="section level2">
<h2>Estadística y metrología</h2>
<p>La ciencia <strong>estadística</strong> busca reducir el error,
resultante de una estimación con su valor verdadero, con el objeto de
tener valoraciones confiables como por ejemplo:</p>
<ul>
<li><p>En economía predecir el precio futuro de una divisa o
acción</p></li>
<li><p>Predecir la temperatura de un día</p></li>
</ul>
<p>En la vida cotidiana, nos interesan muchas medidas como:</p>
<ul>
<li><p>El tiempo que debemos hervir un huevo</p></li>
<li><p>El límite máximo de velocidad</p></li>
<li><p>El peso del equipaje permitido en un avión</p></li>
<li><p>El número de galones con que se tanquea el carro</p></li>
</ul>
<p>La <strong>metrología</strong> es la ciencia que se ocupa de mantener
y aumentar la precisión de las mediciones, en cualquier campo, por
ejemplo</p>
<ul>
<li><p>Obtener una estimación fiable de niveles traza de contaminantes
alimentarios como el mercurio en el pescado</p></li>
<li><p>En el campo de la medicina tener mediciones de la presión
arterial para el diagnostico de enfermedades.</p></li>
</ul>
<pre><code>Una medición cuidadosa puede significar, que una teoría aceptada necesita revisión o que se requiere un nuevo diseño en algún componente crítico de una aeronave.</code></pre>
<div id="tipos-de-metrología" class="section level3">
<h3>Tipos de metrología</h3>
<p><strong>Legal</strong></p>
<p>Se relaciona con las actividades que se derivan de los requisitos
legales que se aplican a la medición, las unidades de medida, los
instrumentos de medida y los métodos de medida que se llevan a cabo por
los organismos competentes.</p>
<p><strong>Científica</strong></p>
<p>Se encarga de la custodia, mantenimiento y trazabilidad de los
patrones, así como la investigación y desarrollo de nuevas técnicas de
medición, de acuerdo al estado del arte de la ciencia.</p>
<p>Dentro de sus funciones se encuentra</p>
<ul>
<li><p>Determinaciones de las constantes físicas fundamentales</p></li>
<li><p>Caracterísiticas de los fenomenos</p></li>
<li><p>Busca mejorar sistemas de medición para lograr un control cada
vez más rápido y más confiable de la mano con el sistema de medidas
internacionales SI</p></li>
</ul>
<p><strong>Técnica o industrial</strong></p>
<p>Comprende todas las actividades metrológicas que necesita la
industria para cumplir con sus tareas como:</p>
<p>– La información sobre mediciones.</p>
<p>– Las calibraciones.</p>
<p>– La trazabilidad.</p>
<p>– El servicio de calibración.</p>
<p>– El aseguramiento de la calidad.</p>
</div>
</div>
<div id="incertidumbre-y-tolerancia-en-las-medidas"
class="section level2">
<h2>Incertidumbre y tolerancia en las medidas</h2>
<p>Las medidas llevan asociado un error desconocido; al que se le asigna
una cota superior, llamada incertidumbre.</p>
<p><span class="math display">\[medida ± incertidumbre \]</span></p>
<p><strong>Incertidumbre</strong></p>
<ul>
<li><p>Parámetro asociado al resultado de una medición que caracteriza
la dispersión de los valores que podrían ser atribuidos al mensurando,
(ISP, 2010)</p></li>
<li><p>Es el intervalo de los valores posibles de una medida.</p></li>
</ul>
<p><strong>Tolerancia (de una magnitud)</strong></p>
<p>Es el intervalo de valores en el que debe encontrarse una magnitud
para que se acepte como válida.</p>
<p><img src="imagen/tol.png" width="261" style="display: block; margin: auto;" /></p>
<p><span class="math display">\[Intervalo \quad toleracia \geq
error+incertidumbre\]</span></p>
<p><strong>Mensurando:</strong> Cantidad destinada a la medida.
(VIM)</p>
<p><strong>Ejemplo</strong></p>
<p>En un experimento se ha medido la gravedad, obteniendo como resultado
<span class="math inline">\((9,51 ± 0,45) m/s^2\)</span>, esto da a
entender que:</p>
<ul>
<li><p>no se puede asegurar que el valor de la gravedad sea <span
class="math inline">\(9,51 m/s^2\)</span></p></li>
<li><p>se puede afirmar que hay un margen de error de <span
class="math inline">\(0,45 m/s^2\)</span>, ya sea por exceso o por
defecto.</p></li>
</ul>
<p>Las mediciones precisas garantizan la confiabilidad de los procesos,
sin embargo la precisión depende del contexto</p>
<p><img src="imagen/balanza.png" width="513" style="display: block; margin: auto;" /></p>
<p><strong>Exactitud de medida</strong></p>
<p>¿Que tan cercano esta al valor verdadero?</p>
<p>Proximidad entre un valor medido y un valor verdadero de un
mensurando</p>
<p><strong>Precisión de medida (VIM)</strong></p>
<p>¿Qué tan cercanas están las medidas entre ellas?</p>
<p>Capacidad que tiene un equipo de replicar un valor, así sea el
verdadero u otro diferente, se expresa mediante medidas de dispersión
tales como la desviación típica, la varianza o el coeficiente de
variación bajo las condiciones especificadas.</p>
<p>Proximidad entre los valores medidos obtenidos en mediciones
repetidas de un mismo objeto bajo condiciones específicas de
repetibilidad, de precisión intermedia, o de reproducibilidad.</p>
<pre><code>## Linking to librsvg 2.48.8</code></pre>
<div id="htmlwidget-f00be60432aa64ba8ef4" style="width:672px;height:480px;" class="grViz html-widget"></div>
<script type="application/json" data-for="htmlwidget-f00be60432aa64ba8ef4">{"x":{"diagram":"digraph{\n \n      graph[rankdir = LR]\n  \n      node[shape = rectangle, style = filled]\n  \n    \n      node[fillcolor = Violet, margin = 0.2]\n      D[label = \"Condiciones especificas\"]\n      \n  \n      subgraph cluster_0 {\n        graph[shape = rectangle]\n        style = rounded\n        bgcolor = Gold\n    \n         label = \"De Repetibilidad\"\n        node[shape = rectangle, fillcolor = LemonChiffon, margin = 0.25]\n        F[label = \"En un periodo corto de tiempo el mismo: \n- Procedimiento de medida,      \n- Operadores\n- Sistema de medida, \n- Condiciones de operación \n- Lugar\n- Objeto o uno similar\"]\n      }\n      \n      subgraph cluster_2 {\n        graph[shape = rectangle]\n        style = rounded\n        bgcolor = Gold\n    \n         label = \"De precisión intermedia\"\n        node[shape = rectangle, fillcolor = LemonChiffon, margin = 0.25]\n         G[label = \"Mismas condiciones de repetibilidad\n         pero con algunas variaciones como nuevas:\n         - Calibraciones\n         - Patrones \n         - Operadores \n         - Sistemas de medida\"]\n      }\n  \n      subgraph cluster_3 {\n         graph[shape = rectangle]\n         style = rounded\n         bgcolor = Gold\n    \n         label = \"De reproducibilidad\"\n         node[shape = rectangle, fillcolor = LemonChiffon, margin = 0.25]\n         H[label = \"Mediciones repetidas de los mismos\n         objetos u otros similares en diferentes \n         - Lugares\n         - Operadores\n         - Sistemas de medida \"]\n         \n      }\n      edge[color = black, arrowhead = vee, arrowsize = 1.25]\n      \n      D -> F    D -> G  D -> H\n      \n      }","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
<p><img src="imagen/dina.png" width="80%" style="display: block; margin: auto;" /></p>
<p>R y R son conocidas después de tomar las mediciones.</p>
<p><strong>Calibración </strong></p>
<ul>
<li><p>Operación que bajo condiciones especificas establece una relación
entre los valores y sus incertidumbres de medida
asociadas(VIM).</p></li>
<li><p>Conjunto de operaciones por comparación entre un patrón y un
instrumento de prueba para determinar el error máximo y su incertidumbre
asociada, va documentado en un certificado de calibración.</p></li>
<li><p>Comparación documentada entre el dispositivo de medición que se
va a calibrar y otro de referencia trazable (BIPM, Bureau International
des Poids et Mesures, es decir, la oficina internacional de pesos y
medidas).</p></li>
<li><p>Descalibración no existe</p></li>
<li><p>Una calibración puede expresarse mediante una declaración, una
función de calibración, un diagrama de calibración, una curva de
calibración o una tabla de calibración.</p></li>
<li><p>El estado de nuevo o usado no lo excluye de la
calibración</p></li>
<li><p>Previo a una calibración el equipo debe estar en óptimas
condiciones de funcionamiento.</p></li>
</ul>
<p><strong>Cerificado de calibración</strong></p>
<p>Documento que muestra las diferencias de medida entre el instrumento
a calibrar (mensurando) y el patrón contra el que se contrasta.</p>
<p><strong>Qué debe contener un certificado de calibración</strong></p>
<ul>
<li><p>Nombre del equipo</p></li>
<li><p>Resolución</p></li>
<li><p>Rango</p></li>
<li><p>Método de calibración</p></li>
<li><p>Incertidumbre del mensurando</p></li>
<li><p>Qué voy a medir?</p></li>
<li><p>Con que instrumento voy a medir</p></li>
<li><p>Diferencias entre las medidas que muestra el instrumento a
calibrar (mensurando)</p></li>
<li><p>Según <strong>La norma ISO/IEC 17025</strong> debe incluir el
método utilizado, en términos de su origen como método directo o
indirecto.</p></li>
<li><p>Patrones contrastados</p></li>
<li><p>Incertidumbre de medida de cada punto contrastado.</p></li>
</ul>
<p><img src="imagen/certi.png" width="100%" style="display: block; margin: auto;" /></p>
<p><strong>Comprobación metrológica</strong></p>
<p>Intermedio entre calibraciones</p>
<p><strong>Trazabilidad metrológica (VIM)</strong></p>
<p>Propiedad de un resultado de medida, que puede relacionarse con una
referencia, mediante una cadena ininterrumpida y documentada de
calibraciones, que contribuyen a la medición de la incertidumbre.</p>
</div>
<div id="normas-y-organizaciones-metrológicas" class="section level2">
<h2><strong>Normas y organizaciones metrológicas</strong></h2>
<table>
<colgroup>
<col width="17%" />
<col width="46%" />
<col width="35%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Abreviatura</th>
<th align="left">significado</th>
<th align="center">autor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">VIM</td>
<td align="left">Vocabulario internacional de metrología</td>
<td align="center">JCGM* Comité Conjunto para las Guías en Metrología
(JCGM por sus siglas en inglés),</td>
</tr>
<tr class="even">
<td align="center">GUM</td>
<td align="left">guia para la expresión de la incertidumbre de las
medidas</td>
<td align="center">ISO</td>
</tr>
<tr class="odd">
<td align="center">ICONTEC</td>
<td align="left"></td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">Norma 10012 (2003)</td>
<td align="left">Gestión de las mediciones</td>
<td align="center">ISO</td>
</tr>
<tr class="odd">
<td align="center">IS</td>
<td align="left">sistema internacional de las medidas</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">ONAC</td>
<td align="left"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">ISO/IEC 17025:2006</td>
<td align="left">Establece los criterios para los laboratorios que
desean demostrar su competencia técnica, que poseen un sistema de
calidad efectivo y que son capaces de producir resultados técnicamente
válidos (McIntyre, J. D. y Honsa., 2000).</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">ISO</td>
<td align="left">organización internacional de estandarización -
International Standardisation Organisation)</td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p>*BIPM, IEC, IFCC, ILAC, ISO, IUPAC, IUPAP y OIML</p>
<div id="norma-10012" class="section level3">
<h3><strong>Norma 10012</strong></h3>
<p><strong>Verificación metrológica</strong></p>
<p>Acto administrativo siguiente después de haber calibrado un equipo,
en el que se comparan las características metrologicas de un equipo de
medición y los requisitos metrológicos del cliente, (Ver Norma
10012)</p>
<p><img src="imagen/n10.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="cómo-medir-la-incertidumbre-de-una-medida"
class="section level2">
<h2>¿Cómo medir la incertidumbre de una medida?</h2>
<p>El resultado de una medición suele ser un número expresado como
múltiplo de una unidad de medida. Para la cuantificación de las medidas
la ISO creo la guia para la expresión de la incertidumbre de las
medidas. <strong>(GUM)</strong>, actualizada en el año 1995.</p>
<div id="sistema-internacional-de-medida-si" class="section level3">
<h3><strong>Sistema internacional de medida (SI)</strong></h3>
<p>Para comunicar los resultados de las mediciones de manera efectiva y
eficiente, los científicos e ingenieros acordaron el sistema
internacional de medidas SI, este sistema es integral, aceptado y
adoptado internacionalmente, coherente y cómodo de usar y revisado
periódicamente.</p>
<table>
<thead>
<tr class="header">
<th align="left">Cantidad</th>
<th align="center">Unidad</th>
<th align="center">Simbolo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Masa</td>
<td align="center">Kilogramo</td>
<td align="center">kg</td>
</tr>
<tr class="even">
<td align="left">Tiempo</td>
<td align="center">Segundo</td>
<td align="center">s</td>
</tr>
<tr class="odd">
<td align="left">Longitud</td>
<td align="center">Metro</td>
<td align="center">m</td>
</tr>
<tr class="even">
<td align="left">Temperatura termodinamica</td>
<td align="center">Kelvin</td>
<td align="center">k</td>
</tr>
<tr class="odd">
<td align="left">Corriente electrica</td>
<td align="center">Amperio</td>
<td align="center">A</td>
</tr>
<tr class="even">
<td align="left">Intensidad luminosa</td>
<td align="center">Candela</td>
<td align="center">sd</td>
</tr>
<tr class="odd">
<td align="left">Cantidad de sustancia</td>
<td align="center">mole</td>
<td align="center">mol</td>
</tr>
</tbody>
</table>
<p>Existen otras medidas derivadas de las anteriores.</p>
<p><strong>Ejemplo</strong> Muestre que la unidad derivada de N/m , la
cual es la medida de la tensión sobre una superficie puede ser expresada
como <span class="math inline">\(kg*s^{-2}\)</span></p>
<p><span
class="math display">\[\frac{N}{m}=\frac{kg*m*s^{-2}}{m}=kg*s^{-2}\]</span></p>
<p>También existen los <strong>prefijos</strong>, que expresan con
abreviaturas cantidades muy pequeñas o muy grandes</p>
<p><strong>Ejemplo</strong></p>
<p><span class="math display">\[3.4*10^{-3} A\]</span> podría escribirse
como 3.4 mA</p>
<p><strong>Ejercicio</strong> 1. Escriba la medida con las unidades de
cantidad base</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(F/m\)</span></th>
<th align="center"><span class="math inline">\(W/m^2\)</span></th>
<th align="center"><span class="math inline">\(J/m^3\)</span></th>
<th align="center"><span class="math inline">\(J/K\)</span></th>
<th align="center"><span class="math inline">\(\Omega*m\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(\Omega/m^2\)</span></td>
<td align="center"><span class="math inline">\(W/(m^2·K^4)\)</span></td>
<td align="center"><span class="math inline">\(N*m\)</span></td>
<td align="center"><span class="math inline">\(C^2/(N·m^2)\)</span></td>
<td align="center"><span class="math inline">\(N/A^2\)</span></td>
</tr>
</tbody>
</table>
<ol start="2" style="list-style-type: decimal">
<li>Escriba las siguientes cantidades con los prefijos</li>
</ol>
<ul>
<li><p><span class="math inline">\(6.4 × 10^{−5} m^2/s\)</span></p></li>
<li><p><span class="math inline">\(7.5 × 10^8\Omega\)</span></p></li>
<li><p><span class="math inline">\(1.8 × 10^{10} Pa\)</span></p></li>
<li><p>$ 3.5 × 10^5 m$</p></li>
</ul>
</div>
</div>
<div id="fuentes-de-incertidumbre-en-las-medidas"
class="section level2">
<h2>Fuentes de incertidumbre en las medidas</h2>
<div id="htmlwidget-0773d3e3b17094902e7f" style="width:672px;height:480px;" class="grViz html-widget"></div>
<script type="application/json" data-for="htmlwidget-0773d3e3b17094902e7f">{"x":{"diagram":"digraph{\n \n      graph[rankdir = LR]\n      node[shape = rectangle, style = filled]\n      node[fillcolor = Violet, margin = 0.2]\n      D[label = \"Evitables\"]\n      E[label = \"Inevitables\"]\n  \n      subgraph cluster_0 {\n        graph[shape = rectangle]\n        style = rounded\n        bgcolor = Gold\n        label = \"Sistemáticas\"\n        node[shape = rectangle, fillcolor = LemonChiffon, margin = 0.25]\n        F[label = \"Aparatos mal calibrados,\n        vidrios dilatados por calentamiento, \n        equipos mal cuidados, \n        errores de método, etc.\"]\n      }\n      \n      subgraph cluster_2 {\n        graph[shape = rectangle]\n        style = rounded\n        bgcolor = Gold\n    \n         label = \"Personales\"\n        node[shape = rectangle, fillcolor = LemonChiffon, margin = 0.25]\n         G[label = \"Inexperiencia del operador,\n        equivocación de un reactivo,\n        lecturas erróneas,\n        brusquedad en el uso de aparatos\"]\n      }\n  \n      subgraph cluster_1 {\n         graph[shape = rectangle]\n         style = rounded\n         bgcolor = Gold\n    \n         label = \"Aleatorias\"\n         node[shape = rectangle, fillcolor = LemonChiffon, margin = 0.25]\n         I[label = \"Reflejan la dispersión de la\n         magnitud al repetir su medida\"]\n      }\n  \n  subgraph cluster_3 {\n         graph[shape = rectangle]\n         style = rounded\n         bgcolor = Gold\n    \n         label = \"instrumentales\"\n         node[shape = rectangle, fillcolor = LemonChiffon, margin = 0.25]\n         H[label = \"Debido a la sensibilidad de los\ndispositivos de medida.\"]\n         \n      }\n      edge[color = black, arrowhead = vee, arrowsize = 1.25]\n      \n      D -> F    D -> G\n      E -> H    E -> I \n      \n      }","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="incertidumbre-en-la-medida" class="section level2">
<h2>Incertidumbre en la medida</h2>
<p><strong>Incertidumbre absoluta</strong></p>
<p>Dada una medida experimental de una magnitud, a, y una incertidumbre
absoluta, <span class="math inline">\(u_a\)</span>; el valor verdadero,
A, debe estar contenido, con razonable certeza, dentro del siguiente
intervalo:</p>
<p><span class="math display">\[a-u_a\leq A \leq a+ u_a \]</span></p>
<p><strong>Incertidumbre relativa</strong></p>
<p>Es el cociente entre la incertidumbre absoluta y el valor de la
medida, es una cantidad adimensional que nos informa de la precisión de
la medida. Suele expresarse (multiplicándola por 100) como
porcentaje.</p>
<p><span class="math display">\[\frac{u_a}{a}\]</span></p>
</div>
<div id="redondeo-y-cifras-significativas" class="section level2">
<h2>Redondeo y cifras significativas</h2>
<iframe width="280" height="160" src="https://www.youtube.com/embed/W1-LgkocIfs" title="⭐ Cifras significativas y REDONDEO de la Incertidumbre de medición - CON EJEMPLOS" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
</iframe>
<p>Se ha medido una distancia como 1,1451 m, se consideran suficientes 3
cifras significativas, cual es el valor al que se debe redondear?</p>
<p>¿1.14 ó 1.15? ¿Cuál es mas cercano?</p>
<p>Cuando se realizan mediciones, ¿cuántas cifras se deben informar? Los
instrumentos modernos son capaces de mostrar valores de muchas cifras.
Como ejemplo, un multímetro digital?</p>
<p><img src="imagen/multimetro.png" width="142" style="display: block; margin: auto;" /></p>
<p>Aveces es prudente registrar todas las cifras proporcionadas por un
instrumento, en muchos casos todas las cifras carecen de
significado.</p>
<p><strong>Regla 1</strong> La incertidumbre aproximada de un valor se
puede estimar como la mitad del rango posible de valores.</p>
<p>Por ejemplo supongamos una distancia se encuentra entre los valores
(25,15−25,05)m=0,10 metros. La mitad de este intervalo es de 0,05 m.
Entonces la distancia es d = 25,1 m, con una incertidumbre de 0,05 m. La
incertidumbre proporcional es:</p>
<p><span class="math display">\[\frac{0,05}{25,1}=0.2%\]</span></p>
<p><strong>Regla 2</strong></p>
<p>Cuando se multiplican, dividen, suman o restan valores, la
incertidumbre resultante es la más cercana a la mayor de las
incertidumbres proporcionales de las componentes.</p>
<p>Por ejemplo, supongamos una velocidad v, cuando la distancia d = 25,1
m y el tiempo necesario es t = 3,4 s. La distancia d tiene una
incertidumbre de 0,2%, mientras que el tiempo t tiene una incertidumbre
de 1,7%. Escribimos, provisionalmente, la velocidad resultante es:</p>
<p><span class="math display">\[v=\frac{d}{t}=\frac{25.1 m}{3.4 s}=7.382
353 m/s \]</span></p>
<p>La mayor de las incertidumbres de los componentes es 1,7%.Las
incertidumbres proporcionales implícitas resultantes., se muestran en
las siguiente tabla</p>
<table>
<thead>
<tr class="header">
<th align="center">Valor aproximado</th>
<th align="left">Diferencia</th>
<th align="center">Incertidumbre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">7.38</td>
<td align="left">0.002</td>
<td align="center">0.032%</td>
</tr>
<tr class="even">
<td align="center">7.4</td>
<td align="left">0.018</td>
<td align="center">0.238%</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="left">0.382353</td>
<td align="center">5.4%</td>
</tr>
</tbody>
</table>
<p>De estas posibilidades, deberíamos elegir el 0,2% como el más cercano
al 1,7% requerido, por lo que citamos la velocidad como 7,4 m/s.</p>
</div>
<div id="metodos-de-medición" class="section level2">
<h2>Metodos de medición</h2>
<p>Descripción genérica de la secuencia lógica de operaciones utilizadas
en una medición.</p>
<p>La norma internacional ISO/IEC 17025 identifica los métodos en
términos de su origen, mientras que VIM los clasifica seún el
fenómeno.</p>
<p><img src="imagen/mm.png" width="666" style="display: block; margin: auto;" /></p>
<p><strong>Preguntas</strong></p>
<ol style="list-style-type: decimal">
<li><p>¿Qué es la metrología?</p></li>
<li><p>Tipos de metrología</p></li>
<li><p>¿Qué es calibración?</p></li>
<li><p>¿Qué es incertidumbre?</p></li>
<li><p>¿Qué es el error?</p></li>
<li><p>¿Qué es tolerancia?</p></li>
<li><p>¿Que es incertidumbre?</p></li>
<li><p>Qué es verificación metrológica?</p></li>
<li><p>qué normas conoces de metrología</p></li>
</ol>
</div>

<br>
<hr>
<p><center>Copyright &copy; 2019, webpage made with Rmarkdown.</center></p>
<hr>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4,h5",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
