---
  title: "Estadística Básica"
---

## Hola a todos Bienvenidos 


```{r fig.asp=0.6, fig.align='center', echo=FALSE}
library(png)
library(grid)
img2 <- readPNG("img2.png")
grid.raster(img2)

```

### Documentos de interés:



- [Compromiso académico](https://github.com/estadisticaITM/repositorioprueba/blob/master/compromiso.pdf)

- [Día a día](https://github.com/estadisticaITM/repositorioprueba/blob/master/DIA-%20DIA_ESTADISTICA_BASICA_2017-2oficial%20adriana%20guerrero.pdf)

- [Microcurrículo](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/FDE%20058%20Microcurriculo%20Estad%C3%ADstica%20Basica%202016...docx%20(1)%20(1).docx)



### Temáticas del curso


### **Estadística descriptiva**

estadística descriptiva <a href="descriptiva.html" target="_blank"> Clase de estadística descriptiva</a>


- [Clase de Análisis exploratorio de datos](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/Presentaci%C3%B3n%20del%20curso%20estad%C3%ADstica%20basica2.pdf)

-Videos




*Medidas de tendencia central*

<iframe width="280" height="160" src="https://www.youtube.com/embed/0DA7Wtz1ddg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Medidas de variabilidad*

<iframe width="280" height="160" src="https://www.youtube.com/embed/cg4kUsbjQms" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


*Cómo estimar la media, la desviación estandar en la calculadora*

<iframe width="280" height="160" src="https://www.youtube.com/embed/4eXrcn6QLgs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


<iframe width="280" height="160" src="https://www.youtube.com/embed/6jqoucoas8Y" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


*Medidas de tendencia central en tablas de frecuencia*

<iframe width="280" height="160" src="https://www.youtube.com/embed/S0sVP_rUt9s" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


### **Regresión lineal**

<a href="reg.html" target="_blank"> Clase de regresión</a>

<a href="taller-regresión.html" target="_blank"> Taller de regresión</a>

### **Probabilidad**

- [Clase de probabilidad](https://github.com/estadisticaITM/repositorioprueba/blob/master/Probabilidad.pdf)


- <a href="tallerprob.html" target="_blank"> Taller de probabilidad</a>


- Videos de técnicas de conteo

*Regla de la multiplicación*

<iframe width="280" height="160" src="https://www.youtube.com/embed/OuZioEJruUg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Permutación*

<iframe width="280" height="160" src="https://www.youtube.com/embed/GSldM3plWD8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Combinación*

<iframe width="280" height="160" src="https://www.youtube.com/embed/vIx-VihHKGs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>




*Cómo estimar combinatorias y permutaciones en la calculadora*

<iframe width="280" height="160" src="https://www.youtube.com/embed/q0TNGY2xMrM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


- Videos de probabilidades

*¿Qué es una probabilidad?*

<iframe width="280" height="160" src="https://www.youtube.com/embed/6RO5mdTz-sI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


*Independencia de eventos*

<iframe width="280" height="160" src="https://www.youtube.com/embed/d4yIg-nEk-M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Regla de la adición*

<iframe width="280" height="160" src="https://www.youtube.com/embed/3-zOxkssUoc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Probabilidad condicional*

<iframe width="280" height="160" src="https://www.youtube.com/embed/iRvdGXnMqeQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="280" height="160" src="https://www.youtube.com/embed/ifTWwKH8AT0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Regla de la probabilidad total*

<iframe width="280" height="160" src="https://www.youtube.com/embed/3h29_gTdZGQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


*Teorema de Bayes*

<iframe width="280" height="160" src="https://www.youtube.com/embed/yWUTaQOwjxU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>




### **Distribuciones discretas**

- [Clase de Distribuciones discretas](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/ITM_VAD_EBX.pptx)

- [Taller de distribuciones discretas](https://github.com/estadisticaITM/repositorioprueba/blob/master/Taller%20para%20el%20tercer%20parcial.docx)

- **Videos de interés**


*Variable aleatoria discreta*


- <iframe width="280" height="160" src="https://www.youtube.com/embed/cfNqJcNU7aI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

-[Video de variable aleatoria discreta](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/myvideooooppppppppppppppppppppp.mp4)


- <iframe width="280" height="160" src="https://www.youtube.com/embed/ip-y-YW5Kg8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Propiedades de la esperanza y de la varianza*
<iframe width="280" height="160" src="https://www.youtube.com/embed/0kowS0mEOcU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="280" height="160" src="https://www.youtube.com/embed/YiHzJgg0OB8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="280" height="160" src="https://www.youtube.com/embed/I6Gcr5BUJt4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


*Distribución de bernoulli*

<iframe width="280" height="160" src="https://www.youtube.com/embed/TX2ga6fZxxM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Distribución binomial*

<iframe width="280" height="160" src="https://www.youtube.com/embed/G1w5gZZaAOg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Distribución de poisson*

<iframe width="280" height="160" src="https://www.youtube.com/embed/lD7RPownwBg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Distribución hipergeométrica*

<iframe width="280" height="160" src="https://www.youtube.com/embed/h8YfFdsHqFA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


*Comparación de distribuciones discretas*

<iframe width="280" height="160" src="https://www.youtube.com/embed/JWRTMeJg70I" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### **Distribuciones continuas**

- [Distribuciones continuas](https://github.com/estadisticaITM/repositorioprueba/blob/master/FUNCIONES%20DE%20DISTRIBUCI%C3%93N%20DE%20PROBABILIDAD%20CONTINUAS.pdf)


- [Taller de distribuciones continuas](https://github.com/estadisticaITM/repositorioprueba/blob/master/taller%20de%20distribuciones%20continuas.pdf)

- Videos de funciones de distrbución de probabilidad continuas


*Función de distribución de probabilidad continua*

<iframe width="280" height="160" src="https://www.youtube.com/embed/wmgia4DoqOk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


*Comparación de distribuciones acumuladas de funciones discretas y continuas*

<iframe width="280" height="160" src="https://www.youtube.com/embed/RLfeCcL_VRE?list=RDCMUCgIxQrfuRANSttW8Dd85j9g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


*Comparación de  la esperanza de funciones discretas y continuas*

<iframe width="280" height="160" src="https://www.youtube.com/embed/WZ0BSrPsEzk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Distribución normal*

<iframe width="280" height="160" src="https://www.youtube.com/embed/3mikDVlYiok" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="280" height="160" src="https://www.youtube.com/embed/tFlKqPVfVU8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


### **Trabajo final **

<a href="posterestdesc.html" target="_blank"> Pautas para el poster</a>



### **Las tablas las puedes encontrar**

[Aqui](https://github.com/estadisticaITM/repositorioprueba/blob/master/tabla%20de%20diferentes%20probabilidades.pdf)



### BIBLIOGRAFÍA

- Probabilidad y estadística para ingeniería y ciencias Jay L. Devore

- Guerrero P, A., Buitrago C, M. V., & Curieses P, M. d. (2010). Estadistica Basica (2da ed.). Medellin: Fondo Editorial ITM. [Libro](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/Estadistica%20basica%202010%20%20libro.pdf)


