
---
title: "ESTADÍSTICA INFERENCIAL"
---


```{r fig.asp=0.6, fig.align='center', echo=FALSE}

library(png)
library(grid)
img2 <- readPNG("exp.png")
grid.raster(img2)

```



## Documentos de interés

[Microcurrículo](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/FDE%20058%20Microdise%C3%B1o%20curricular%20V03%20(2).docx)

[Compromiso académico](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/compromiso%20dise%C3%B1o.docx)



## Orden del curso

El orden de los temas que se llevará en el curso es:

1. Repaso de estadística descriptiva [Clase](https://github.com/estadisticaITM/repositorioprueba/blob/master/repaso%20estad%C3%ADstica%20b%C3%A1sica.pptx)

- Aspectos generales y gráficos

- Análisis descriptivo en excel 

- Introducción al R

 [Video](https://github.com/estadisticaITM/repositorioprueba/blob/master/index.mp4) y [Clase]({https://github.com/estadisticaITM/repositorioprueba/blob/master/Semillero%20de%20R%20clase%201.pdf})

2. Muestreo [clase](https://github.com/estadisticaITM/repositorioprueba/blob/master/Tama%C3%B1os%20de%20muestra.pdf)


#### Videos de tamaños de muestra


#### Para la media

  <iframe width="280" height="158" src="https://www.youtube.com/embed/JX5m7o6rOAQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
 </div>


#### Para la proporción

  <iframe width="280" height="158" src="https://www.youtube.com/embed/4G2kKHX5O8U" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


3. Intervalos de confianza

[clase](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/Intervalos%20de%20confianzajtg.pdf)

[Fórmulas](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/f%C3%B3rmulas.pdf)

- Algunos videos de interés

*Estimación puntual y por intervalo*

<iframe width="280" height="160" src="https://www.youtube.com/embed/cMqgG_lBC2U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Distribución t de student*

<iframe width="280" height="160" src="https://www.youtube.com/embed/wGSutshZDiA?list=RDCMUCMLQ_dQirjjwPjR8skwX3gA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Qué es el nivel de confianza*

<iframe width="280" height="160" src="https://www.youtube.com/embed/YDFzX4fT1BU?list=RDCMUCMLQ_dQirjjwPjR8skwX3gA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


*Intervalo de confianza para la media con varianza conocida*

<iframe width="280" height="160" src="https://www.youtube.com/embed/tnDFgEv_a-I?list=RDCMUCMLQ_dQirjjwPjR8skwX3gA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Intervalo de confianza para la proporción*

<iframe width="280" height="160" src="https://www.youtube.com/embed/oJv6d9IECRo?list=RDCMUCMLQ_dQirjjwPjR8skwX3gA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Intervalo de confianza para la varianza*

<iframe width="280" height="160" src="https://www.youtube.com/embed/Pw66ZHxzAF4?list=RDCMUCMLQ_dQirjjwPjR8skwX3gA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Intervalo de confianza para la diferencia de medias con varianzas iguales*

<iframe width="280" height="160" src="https://www.youtube.com/embed/aMOINMuUXVc?list=RDCMUCMLQ_dQirjjwPjR8skwX3gA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Intervalo de confianza para la diferencia de medias con varianzas desconocidas y diferentes*

<iframe width="280" height="160" src="https://www.youtube.com/embed/YIImQIRDGMg?list=PLfX5C7cc6LRKG-OUUatElez6mzu1B9UjR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Intervalo de confianza para la razón de varianzas*

<iframe width="280" height="160" src="https://www.youtube.com/embed/SzXfVJbPh-0?list=PLfX5C7cc6LRKG-OUUatElez6mzu1B9UjR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Intervalo de confianza para la diferencia de proporciones*

<iframe width="280" height="160" src="https://www.youtube.com/embed/Bwbe7cvkDn4?list=PLfX5C7cc6LRKG-OUUatElez6mzu1B9UjR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

*Intervalo de confianza para la diferencia de medias pareadas*

<iframe width="280" height="160" src="https://www.youtube.com/embed/hcEaKfN28Y0?list=PLfX5C7cc6LRKG-OUUatElez6mzu1B9UjR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


4. Pruebas de hipótesis

[Clase](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/pruebas%20de%20hip%C3%B3tesis%20JTG.pdf)  

[Intervalos de confianza y test de hipótesis con R](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/INTERVALOS%20DE%20CONFIANZA%20Y%20TEST%20DE%20HIPOTESIS%20CON%20R.pdf)

- Algunos videos de interés

*Pasos para realizar una prueba de hipótesis*
<iframe width="280" height="160" src="https://www.youtube.com/embed/zP6JsuHm9Hg?list=RDCMUCMLQ_dQirjjwPjR8skwX3gA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



5. Pruebas no paramétricas <a href="pruebas_no_paramétricas.html" target="_blank"> Clase de pruebas no paramétricas</a>

7. Regresión lineal <a href="regrelineal.html" target="_blank"> Clase de regresión</a>

8. **Diseño de experimentos **

- <a href="varianza.html" target="_blank"> Introducción al análisis de varianza</a>

- <a href="diseñoazar.html" target="_blank"> Diseño completamente al azar</a>

- <a href="diseñobloque.html" target="_blank"> Diseño en Bloques </a>

- <a href="diseñofactorial.html" target="_blank"> Diseño factorial </a>

## Talleres

1. <a href="wjoanova.html" target="_blank">Trabajo ANOVA</a>
Fecha de entrega: 5 de Junio


2. Taller de tamaños de muestra intervalos de confianza y pruebas de hipótesis 

[Tamaños de muestra, intervalos de confianza, PH](https://github.com/estadisticaITM/repositorioprueba/blob/master/Taller%20de%20tama%C3%B1os%20de%20muestra%2C%20intervalos%20de%20confianza%20y%20ph.pdf)


3. <a href="trabajoregrelineal.html" target="_blank"> Trabajo de regresión lineal </a>

[Plantilla](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/PlantillaTrabajos.doc)

[Datos](https://github.com/estadisticaITM/repositorioprueba/blob/master/APC1modif.txt)


3. Diseño experimental

[Taller](https://github.com/estadisticaITM/repositorioprueba/blob/master/Actividad%203'dise%C3%B1o%20con%202%20factores.doc)

[Datos](https://github.com/estadisticaITM/repositorioprueba/blob/master/produccion2.csv)

