---
title: "Poster de estadística descriptiva"
output:
  html_document:
    toc: true
    toc_depth: 5
    #toc_float:
     # collapsed: falsed
      #smooth_scroll: true
   
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## **Objetivo general:** 

Poner en práctica los conceptos aprendidos en el curso de estadística descriptiva través de la realización de un poster o cartelera del tema de preferencia.

## **Objetivos específicos:**

-	Repasar conceptos de estadística descriptiva

-	Usar las diferentes funciones del software excel

- Número de integrantes: Máximo 2 personas

- Fechas de exposición del poster: Según lo acordado en el compromiso académico

## **Pasos a realizar:**

1. Escoger una base de datos de su preferencia que contenga 2 variables cuantitativas y dos variables cualitativas, (por favor ponerse de acuerdo con el docente), mínimo 500 datos, algunos de las bases de datos de donde se pueden obtener datos son:

- [DANE](https://www.dane.gov.co/index.php/estadisticas-por-tema)

- [BANCO MUNDIAL](https://datos.bancomundial.org/indicador/SH.HIV.0014)

- [Agronet](https://www.agronet.gov.co/estadistica/Paginas/home.aspx) 

- [KAGGLE](https://www.kaggle.com/) 

- [Datos abiertos](https://www.datos.gov.co/) 


## **Calificación**

La calificación de esta actividad se realizará con la siguiente rúbrica, donde cada item vale 3 puntos:

|subtema  |Ítem|Excelente (3 ptos)|Bueno (2 ptos)|Regular (1 ptos)|
|:----------------:|:-------------:|:------------------------:|:------------:|:-----------:|
|________________|________________|________________________|______________|______________|
|  |1. Introducción|De q trata su base, de donde la sacó   |              |              |
|**Estadistica**|2. Clasificación de variables             |              |              |
|**Descriptiva**|3. Boxplot|comparativo de los niveles de factor de DOS variables cualitativas con una variable cuantitativa  |comparativo de los niveles de factor de una variable cualitativa con una variable cuantitativa |de una sola variable cuantitativa sin comparar nada|
|         |4. Torta                      | |  ||
|En excel |5. Grafico de barras con top 5| |  ||
|         |6. Histograma                 | |  ||
|si tiene la variable tiempo|7. Gráfico de series de tiempo ||  ||
|___________|________|_________________|____________|______________|
|**Medidas de tendencia central y de variabilidad (MTCV)**|8. MTCV|Tabla con las MTCV de una variable cuantitativa según los niveles del factor de una variable cualitativa (media, sd, cv)|Tabla con las MTCV de una variable cuantitativa| |
|___________|_______________|_________________|____________|______________|
|**Video de exposición**| 9.| El vídeo se escucha y se visualiza correctamente, con una duración entre 5 y 10 minutos, está subido en youtube. |El vídeo dura menos de 5 min o más de 10 min, video no está en youtube| no entrega video|
|_______________________|________|_______________________|____________|______________|
|**Intervalos**         |10.|Para la media de una muestra   |         |              | 
|**de confianza (IC)**  |11.|Para la varianza de una muestra|         |              |
|**Para una muestra**|12.|Para la proporción de una muestra |         |              |
|___________|________|________________________|_______________________|______________|
|                              |13.|Para la diferencia de medias      |      |       | 
|**IC para dos muestras**      |14.|Para la razón de varianzas        |      |       | 
| Usa editor de ecuaciones word|15.|Para la diferencia de proporciones|      |       | 
|________________________|________|_________________|_________________|______________|
|**Pruebas de hipótesis (PH)** |16.|Para la proporción|              |               | 
|Usa editor de ecuaciones word |17.|Para la diferencia de proporciones|           |  |    
|______________________|_______________|_________________|____________|______________|





## **Entregables**

- Video de 5 minutos con la exposición del poster

- Pdf con el póster



**Observaciones**

-	Los gráficos deben tener títulos de ejes 

-	Cada gráfico debe tener su respectivo análisis.

-	Por cada tílde a corregir se baja la nota 0.1

- en los casos que aplique hacer un top 5

- Contiene título, nombres de los integrantes está bien organizado y ordenado, no hay sobrecarga de texto, ni espacios en blanco, buena ortografía, Bibliografía

- Títulos de ejes legibles, cada grafico contiene un pequeño análisis (5 puntos cada uno)





**Ejemplo**

Se puede apoyar en el siguiente ejemplo:
[Ejercicio en excel](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/PRACTICA.xlsx)

**Videos de interés para la construcción del poster**

*Video de regresión lineal en  excel*

<div style="text-align: center;"><iframe width="280" height="160" src="https://www.youtube.com/embed/nEAvKHStLyU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>

*Video de tablas dinámicas en excel*

<iframe width="280" height="160" src="https://www.youtube.com/embed/2L65YUVP9VQ" title="Tablas dinámicas en excel" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

*Video de gráficos en excel*

<iframe width="280" height="160" src="https://www.youtube.com/embed/ThDQusebRUM" title="Gráficos excel" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


*Video de boxplot*

<iframe width="280" height="160" src="https://www.youtube.com/embed/ggUhQUXc2mI" title="Cómo realizar un Boxplot en excel." frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## **Plantillas**

Ver página canvas