---
title: "Trabajo escrito de estadística inferencial"
output:
  html_document:
    toc: true
    toc_depth: 5
    #toc_float:
     # collapsed: falsed
      #smooth_scroll: true
   
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## **Objetivo general:** 

Poner en práctica los conceptos aprendidos en el curso de estadística descriptiva e inferencial,a través de la realización de un trabajo escrito del tema de preferencia.

## **Objetivos específicos:**

-	Repasar conceptos de estadística descriptiva

- Aplicar los conceptos de estadística inferencial

-	Usar las diferentes funciones del software excel y de R

- Número de integrantes: Máximo 2 personas

- Fechas de entrega del trabajo escrito: Según lo acordado en el compromiso académico

## **Pasos a realizar:**

1. Escoger una base de datos de su preferencia que contenga 3 variables cuantitativas y dos variables cualitativas, mínimo 100 datos, algunos de las bases de datos de donde se pueden obtener datos son:

- [DANE](https://www.dane.gov.co/index.php/estadisticas-por-tema)

- [BANCO MUNDIAL](https://datos.bancomundial.org/indicador/SH.HIV.0014)

- [Agronet](https://www.agronet.gov.co/estadistica/Paginas/home.aspx) 

- [KAGGLE](https://www.kaggle.com/) 

- [Datos abiertos](https://www.datos.gov.co/) 


## **Calificación**

- Cada punto vale 3 puntos 

- Depende de como usted lo realice asi será su calificación

- Si no hace uno de los puntos su calificación será 0

- La calificación de esta actividad se realizará con la siguiente rúbrica:


|**subtema**|**Ítem**|**Excelente (3)**|**Bueno(2)**|**Regular(1)**|
|:-------------------|:-----------|:--------------------------|:-----------|:-------------|
|___________|________|_________________|____________|______________|
|           |1.Introducción |Realiza una descripción de la base de datos |||
|**Estadistica**|2.Clasificación de variables|Hacer una tabla que especifique el tipo de variable. Cuantitativa: Discreta o continua, Cualitativa:Nominal u ordinal|||
|**Estadistica Descriptiva**|3. Boxplot| Ver indicaciones en el video, A PARTIR DEL MIN 12:50 https://www.youtube.com/watch?v=DU4mS1AKRpI, en el que se relacionan una variable continua con dos cualitativas |comparativo de los niveles de factor de una vble cualitativa con una variable cuantitativa |de una sola vble cuantitativa|
|        |4. Torta                      |                 |              |                |
|En excel|5. Grafico de barras con top 5|                 |              |                |
||6. Histograma|Con la tabla y el análisis |Con la tabla y sin analisis|solo el grafico   |
|Si tiene la variable tiempo |7. Gráfico de series de tiempo |        |      |     |      |
|______________|_______________|_________________|_______________|_____________|__________|
|**Intervalos**|8. Para la media|**Debe contener**|              |  |   | 
|**de confianza (IC)**|9. Para la varianza|Enunciado y respuesta|  |   |
|**Para una muestra**|10. Para la proporción|procedimiento con editor de ecuaciones|  |   |
|___________|________|___________________|_________________|______________|
|          |11. Para la diferencia de medias|**Debe contener**| |   | 
|**IC para dos muestras**|12. Para la razón de varianzas|Enunciado y respuesta|      |       | 
||13.Para la diferencia de proporciones|procedimiento con editor de ecuaciones|      |       | 
|________________________|________|_________________|_________________|______________|
|**Pruebas de hipótesis (PH)**|14. Para la proporción|**Debe contener**||| 
|Usa editor de ecuaciones word |15. Para la diferencia de proporciones|Paso a paso visto en clase|||
|______________|_______________|_________|_________________|___________|
|Elija una variable continua y realice lo siguiente|16. Grafico qqnorm |con análisis|Sin análisis (1.5)|||
|**Pruebas no paramétricas**|17. Grafico densidad |Con analisis|sin analisis (1.5) | |
|**En Rstudio**|18.Prueba de normalidad |Escribe el juego de hipotesis y acepta o rechaza normalidad con la prueba de shapiro wilk en R|| |
|__________________|_________|_________________|___________|__________|
|Con dos variables cualitativas |19.Tabla de contingencia |Construye una tabla de doble entrada (conteo de variables) con totales de columnas y filas|||
|**En Rstudio** |20.Prueba de independecia con test exacto de fisher o chi-2 | escribe prueba de hipotesis y verifica la independencia con R| | |
|______________|_______________|_________|_________________|___________|__________|
|**Regresión lineal**|21.Estima una matriz de correlaciones entre por lo menos 3 variables cuantitativas|Estima la matriz de correlaciones con los graficos de dispersión usando la función "chart.Correlation" de la librería performance analytics|Estima una matriz de correlaciones entre por lo menos 3 variables cuantitativas(1.5)| | |
|_____________________|_________|_________________|___________|__________|
|Teniendo en cuenta la mejor correlación entre variables cuantitativas construye lo siguiente |22. Diagrama de dispersión (DD) entre dos variables cuantitativas con la linea superpuesta|Contiene el DD sin la línea recta superpuesta|||
|**Regresión lineal simple RLS**|23. Construye un modelo de RLS entre dos variables cuantitativas, reporta ecn, valor de $R^2$ y valor de r.| |  | |
|**en excel** |24. Interpretación del modelo| |  | |
|_____________|________________________________|___________|_________|____|
|**Regresión lineal multivariada RLM**|25. Ajuste del Modelo de regresión lineal multivariada (MRLM) |Ajuste un MRLM entre por lo menos 3 variables cuantitativas y una cualitativa,incluya tanto variables significativas como no significativas, use la función STEPAIC  reporte la salida de R y ANOVA|||
|**En Rstudio**|26. |Ajuste un MRLM entre por lo menos 2 variables cuantitativas y una cualitativa,incluyendo solo aquellas que son significativas,  reporte la salida de R, asi como la tabla ANOVA|||
|**RLM**|25.Ecuaciones de regresión|A partir del modelo anterior, escriba la recta multivariada general, asi como las rectas ajustadas de cada uno de los niveles y las interpreta|||
|**En Rstudio**|27. **Diagrama de Dispersión (DD)** |DD discriminando con colores los niveles de una variable cualitativa, superpone las lineas rectas estimadas del modelo de regresión con variables indicadoras|||
|**RLM**|28. **Test lineal general**|A partir del ANOVA ajusta el test lineal general mediante la prueba F, para validar significancia de la regresión, escriba prueba de hipotesis y el estadístico|||
|**En Rstudio** |29. validación de la **significancia de los parametros estimados**|Escribe la prueba de hipotesis y construye el estadístico||
||30. **Test lineal general**|Escribe la prueba de hipotesis, construye el estadístico, muestra la salida de R||
|______________|_______________|_________|________________|_________________|___________________|
||31.**4 Graficas de residuales**|Grafica y analisis de comportamiento de residuales|solo grafica|   |
|**Analisis de residuales** |32. **Prueba de normalidad**| Escribe la PH de normalidad sobre los residuales y la verifica con la prueba de shapiro wilk en R| ||
||33. **Prueba de varianza constante**| Escribe la PH y muestra salida de R|  |   |
|______________|_______________|_________|________________|_________________|___________________|
|**Del modelo resultante en 24. son los residuales Normales ?**|34.**Transformaciones**| Ajuste el MRLM con transformacion sobre la variable respuesta, reporte la salida de R|  ||
|**RLM**|35. Ecuaciones de regresión|A partir del modelo anterior, escriba la recta multivariada general|||
||36. **4 Graficas de residuales**|Grafica y analisis de comportamiento de residuales|solo grafica|   |
|**Analisis de residuales**|37. **Prueba de normalidad**| Escribe la PH de normalidad sobre los residuales y la verifica con la prueba de shapiro wilk en R| ||
||38.**Prueba de varianza constante**| Escribe la PH y muestra salida de R|  |   |
|______________|_______________|_________|____________|___________________|________________|
|**Tamaño de muestra (TM)**| 39.| Estima un TM estratificado para los datos que está tratando| Estima un TM para población finita para los datos que está tratando|  Estima un TM para población infinita para los datos que está tratando |
|**Validación cruzada**|40.Comparación|Compara modelo transformado y sin transformar|  |   |
|______________|_______________|_________|_________________|___________|__________|


## **Entregables**

- Trabajo escrito en word o pdf

**Observaciones**

- Para el punto de PH e IC recordar verificación de igualdad de varianzas, para elaborar este punto debe de realizar una tabla con el resumen de las medidas de tendencia central y de variabilidad de las variables que vaya a analizar.

-	Los gráficos deben tener títulos de ejes 

-	Cada gráfico debe tener su respectivo análisis.

-	Por cada tílde a corregir se baja la nota 0.1

- En los casos que aplique hacer un top 5


**Ejemplo**

Se puede apoyar en el siguiente ejemplo:
[Ejercicio en excel](https://github.com/estadisticaITM/estadisticaITM.github.io/blob/master/PRACTICA.xlsx)

**Videos de interés para la construcción del poster**

*Video de regresión lineal en  excel*

<div style="text-align: center;"><iframe width="280" height="160" src="https://www.youtube.com/embed/nEAvKHStLyU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>

*Video de tablas dinámicas en excel*

<iframe width="280" height="160" src="https://www.youtube.com/embed/2L65YUVP9VQ" title="Tablas dinámicas en excel" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

*Video de gráficos en excel*

<iframe width="280" height="160" src="https://www.youtube.com/embed/ThDQusebRUM" title="Gráficos excel" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

*Video de boxplot*

<iframe width="280" height="160" src="https://www.youtube.com/embed/ggUhQUXc2mI" title="Cómo realizar un Boxplot en excel." frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

