
---
title: "Analisis multivariante"
---


# ¿Qué es el análisis multivariado?

Es un conjunto de técnicas para analizar simultáneamente más de una variable.
Usualmente se limita al análisis de variables continuas bajo el supuesto de que provienen de una distribución normal multivariable. (Aproximación clásica al análisis multivariable).


## Definiciones Básicas

**Vector aleatorio:** Contiene la información sobre k variables medidas en un sujeto sacado al azar de una población particular.


$$X= 
\left[ \begin{array}{cc}
 x_1 & \\
 x_2&\\
 .&\\
 .&\\
 .&\\
 x_k &
\end{array} \right] $$



**Muestra:**$x_1, x_2,..., x_n$ sujetos, el i-ésimo sujeto tiene el vector.


$$\Large x_i= 
\left[ \begin{array}{cc}
 x_{i1} & \\
 x_{i2}&\\
 \vdots&\\
 x_{ik} &
\end{array} \right] $$

**Tipos de variables**




```{r fig.asp=0.6, fig.align='center', echo=FALSE}

library(png)
library(grid)
imgm1 <- readPNG("tvrb.png")
grid.raster(imgm1)

```




- Usualmente una base de datos es una combinación de diferentes tipos de variables: Sexo, Edad, Número de hijos, Estado civil, Fecha de nacimiento, etc.

- Para muchos análisis solo trabajamos con un solo tipo de variables, por ejemplo, en el análisis clásico multivariable se asume que se tienen solo variables continuas.

- Si tenemos una variable categórica que indique un grupo podemos subdividir la base de acuerdo a esa variable y realizar los mismos análisis dentro de cada grupo: análisis segmentado.



Asumiendo que todas las variables son continuas.

**Matriz de datos:** Contiene la información sobre n sujetos de la población tomados al azar y a los cuales se les han medido las variables $x_1, x_2,..., x_k$




$$\Large X=\left( \begin{array}{cccc}
 x_{11} & x_{12} & \cdots & x_{1k}  \\ 
 x_{21} & x_{22} & \cdots & x_{2k}\\
 \vdots & \vdots & \ddots & \vdots \\
 x_{n1} & x_{n2} & \cdots & x_{nk}
 
\end{array} \right) $$


**determinante de una matriz**









**Ejemplo**

La siguiente tabla presenta las mediciones realizadas a 10 estudiantes universitarios de sus pies.

Medidas de Pies
|x1     |x2   |x3   |x4   |x5   |
|-------|-----|-----|-----|-----|
|24.2   | 9.4 | 5.5| 3.0| 3.2|
|21.7   | 8.5 | 6.1| 3.2| 2.6|
|25.4   | 9.6 | 5.5| 4.0| 3.1|
|25.0   | 10.1| 5.3| 3.5| 2.7|
|22.0   | 8.5 | 5.7| 3.1| 2.7|
|25.9   | 9.3 | 6.1| 4.3| 3.3|
|22.2   | 8.6 | 5.2| 3.9| 2.9|
|21.7   | 8.4 | 5.0| 3.2| 2.3|
|25.5   | 9.2 | 6.1| 3.3| 3.2|
|24.4   | 9.4 | 4.7| 3.6| 2.8|

Donde

$x_1:$ Longitud máxima del pie

$x_2$: Amplitud máxima del pie

$x_3:$ Amplitud máxima del talón

$x_4:$ Longitud máxima del dedo grande

$x_5:$ Amplitud máxima del dedo grande


Vector de medias muestrales






$$\Large \bar x=\sum_{i=1}^n\frac{1}{n}x_i=\sum_{i=1}^n\frac{1}{n}\left[ \begin{array}{cc}
 x_{i1}\\
 x_{i2}\\
 \vdots\\
 x_{ik}
\end{array} \right] =\left[ \begin{array}{cc}
\bar x_{1} \\
\bar x_{2}\\
 \vdots\\
\bar x_{k}
\end{array} \right] 
$$


Para los datos de los pies tenemos los siguientes resultados:


$$\Large x_i= 
\left[ \begin{array}{cc}
 23.8 \\
 9.1  \\
 5.52 \\
 3.51 \\
 2.88
\end{array} \right] $$




**Matriz de varianzas y covarianzas**



$$\Large S=\left( \begin{array}{cccc}
 s_{11} & s_{12} & \cdots & s_{1k}  \\ 
 s_{21} & s_{22} & \cdots & s_{2k}\\
 \vdots & \vdots & \ddots & \vdots \\
 s_{k1} & s_{k2} & \cdots & s_{kk}
 
\end{array} \right) $$



Donde:


$$\Large S_{ij}=cov(x_i,x_j)=\sum_{k=1}^{n}\frac{(x_{ki}-\bar x_i)(x_{ki}-\bar x_j)}{(n-1)}$$




$$\Large S_{jj}=var(x_j)=\sum_{k=1}^{n}\frac{(x_{kj}-\bar x_j)^2}{(n-1)}$$


La matriz de varianzas y covarianzas para los datos de los pies es:


|Variable  |x1    | x2  |    x3| x4  | x5|
|--|------|-----|------|-----|----|
|x1| 2.94 | 0.83| 0.16 |0.37 |0.42|
|x2| 0.83 |0.33 |-0.03 | 0.08| 0.09|
|x3| 0.16 |-.03 | 0.24 | 0.01| 0.07|
|x4| 0.37 |0.08 |0.01  |0.19 |0.06|
|x5| 0.42 |0.09 |0.07  |0.06 |0.10|


