---
title: "Regresión logística"
output:
  html_document:
    toc: true
    toc_depth: 5
    #toc_float:
     # collapsed: falsed
      #smooth_scroll: true
   
---


Dentro de los algoritmos de clasificación se encuentran los algoritmos supervisados  y no supervisados

Algoritmo supervisado
Algoritmo no supervisado
Datos etiquetados
Datos no etiquetados
el modelo aprende mediante la guía humana
descubren patrones ocultos y agrupaciones de datos, sin requerir intervención humana directa
Se ha logrado entrenar modelos para identificar patrones en datos médicos y realizar diagnósticos precisos en la detección temprana de enfermedades.
Se ha revolucionado el marketing al segmentar mercados, identificando grupos de clientes con características afines y permitiendo estrategias de ventas personalizadas.
Entre algunos algoritmos se encuentran

Regresión Lineal 
Series de Tiempo 
Árboles de Decisión 
Bosques Aleatorios 
Redes Neuronales, 
K Vecinos más Cercanos (KNN) 
Máquinas de Soporte Vectorial (SVM)
Entre algunos algoritmos se encuentran

K-means para la agrupación Apriori, Eclat
FP-Growth para la asociación.







# Regresión logística binomial




#Regresión logística multinomial