---
title: "Taller de regresión lineal"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


1. El Director de admisiones de una universidad aplicó un nuevo test de admisión a 20 estudiantes de primer año seleccionados aleatoriamente, con el fin de determinar si el promedio de notas al final del primer año (GPA) puede ser predicho a partir del puntaje de la prueba de ingreso. Los resultados se presentan en la siguiente tabla.

|Sujeto |nota final|puntaje de ingreso|
|-------|----|------------|
|1 |3.1 | 5.5 |
|2 |2.3 | 4.8 |
|3 |3   | 4.7 |
|4 |1.9 |3.9  |
|5 |2.5 |4.5  |
|6 |3.7 |6.2  |
|7 |3.4 |6    |
|8 |2.6 |5.2  |
|9 |2.8 |4.7  |
|10|1.6 |4.3  |
|11|2   |4.9  |
|12|2.9 |5.4  |
|13|2.3 |5    |
|14|3.2 |6.3  |
|15|1.8 |4.6  |
|16|1.4 |4.3  |
|17|2   |5    |
|18|3.8 |5.9  |
|19|2.2 |4.1  |
|20|1.5 |4.7  |

a. Identifique la variable respuesta y la variable predictora.
b. Estime el modelo de regresión lineal asociado
c. Explique e interprete el significado de $\beta_0$ y $\beta_1$
d. Haga un gráfico de dispersión con la curva de regresión ajustada
e. ¿Es el modelo de regresión apropiado?
 ¿que indica la correlación y el coeficiente de determinación?
f. Obtenga una estimación puntual para estudiantes con un puntaje en la prueba de ingreso de 5.0.




2. Una sustancia empleada en investigación médica y biológica es transportada por carga aérea en cajas de cartón conteniendo 1000 ampollas de la sustancia. En la siguiente tabla se presentan los datos obtenidos para 10 embarques y corresponden a X: número de veces que las cajas son transferidas de un avión a otro en la ruta de embarque y Y : número de ampollas que fueron halladas quebradas a la llegada.


|transferencias	|Ampollas quebradas|
|---------------|------------------|
|1	|16|
|0|	9|
|2|	17|
|0|	12|
|3|	22|
|1|	13|
|0|	8|
|1|	15|
|2|	19|
|0|	11|

a. Obtenga la recta de regresión lineal

b. Obtenga una estimación puntual del número de ampollas quebradas cuando solo una transferencia es hecha durante el transporte.

c. Obtenga el grafico de dispersión junto con la recta estimada. Evalúe la calidad del ajuste.

d Pruebe estadísticamente, la veracidad de la siguiente afirmación: Por cada unidad en que se aumenta el número de transferencias entre aviones realizadas durante el transporte del producto, el numero promedio de ampollas que llegan quebradas a su destino se incrementa en más de 4 unidades.

3. La siguiente base de datos relaciona la longitud y el ancho del sépalo de diferentes especies de iris (flores).

|Especie|	Longitud del sépalo| 	Ancho el sépalo|
|-------|--------------------|-----------------|
|setosa	|5,1|	3,5|
|setosa	|4,9|	3|
|setosa	|4,7|	3,2|
|setosa	|4,6|	3,1|
|setosa	|5	|3,6|
|versicolor|	7	|3,2|
|versicolor	|6,4|	3,2|
|versicolor	|6,9|	3,1|
|versicolor	|5,5|	2,3|
|versicolor	|6,5|	2,8|
|virginica	|6,7|	3|
|virginica	|6,3|	2,5|
|virginica	|6,5|	3|
|virginica	|6,2|	3,4|
|virginica	|5,9|	3|


a. Realice el diagrama de dispersión diferenciando con colores las especies de flores

b. Ajuste el modelo de rgresión apropiado para cada tipo de flor

c. Interprete el valor de la pendiente, del intercepto, la correlacipon y del $R^2$ en cada tipo de flor





