---
title: "Taller Distribuciones de muestreo"
output:
  html_document:
    toc: true
    toc_depth: 5
---

## Teorema central del límite

1. La resistencia a la ruptura del vidrio templado promedia 14 (medida en miles de libras por pulgada cuadrada) y tiene una desviación estándar de 2.

a ¿Cuál es la probabilidad de que el promedio de resistencia a la ruptura de 100 piezas seleccionadas aleatoriamente de este vidrio exceda de 14.5?

b Encuentre un intervalo que incluya, con probabilidad 0.95, el promedio de resistencia a la ruptura de 100 piezas de este vidrio seleccionadas aleatoriamente.

2. Una antropóloga desea calcular el promedio de estatura de los hombres de cierta raza. Si se supone que la desviación estándar poblacional es de 2.5 pulgadas y si ella muestrea 100 hombres aleatoriamente, 

a) encuentre la probabilidad de que la diferencia entre la media muestral y la verdadera media poblacional no exceda de 0.5 pulgada. Rta/0.9544

b) Suponga que la antropóloga desea que la diferencia entre la media muestral y la mediapoblacional sea menor que 0.4 pulgada, con probabilidad de 0.95. ¿Cuántos hombres debe tomar como muestra para lograr este objetivo?

3. Trabajadores de una gran empresa de servicios tienen un salario promedio de 7% por hora con una desviación estándar de 0.5. La industria tiene 64 trabajadores de cierto grupo étnico que tienen un salario promedio de $6.9$ por hora. ¿Es razonable suponer que la tasa salarial del grupo étnico es equivalente a la de una muestra aleatoria de trabajadores tomada de los empleados en la industria militar?
[Sugerencia: calcule la probabilidad de obtener una media muestral menor o igual que $6.9 por hora.Rta/0.0548]

4. La acidez de los suelos se mide mediante una cantidad llamada pH, que varía de 0 (acidez alta) a 14 (alcalinidad alta). Un edafólogo desea calcular el promedio de pH para un campo de grandes dimensiones al seleccionar aleatoriamente n muestras de núcleos y medir el pH de cada muestra. Aun cuando la desviación estándar poblacional de mediciones de pH no se conoce, la experiencia del pasado indica que casi todos los suelos tienen un valor de pH de entre 5 y 8. 

a. Si el científico selecciona n = 40 muestras, encuentre la probabilidad aproximada de que la media muestral de las 40 mediciones de pH esté a 0.2 unidades del verdadero promedio de pH para el campo. [Sugerencia: vea el Ejercicio 1.17.]

b. Suponga que al científico le gustaría que la media muestral estuviera a no más de 0.1 de la verdadera media con probabilidad 0.90. ¿Cuántas muestras de núcleos debe tomar?

5. Un aspecto importante de un plan económico federal era que los consumidores ahorraran una parte importante de dinero que recibieran por una reducción de impuestos sobre sus ingresos. Suponga que las primeras estimaciones de la parte del total de impuesto ahorrada, con base en una muestra aleatoria de 35 economistas, tuvo media de 26% y desviación estándar de 12%. 

a ¿Cuál es la probabilidad aproximada de que la estimación de la media muestral, basada en una muestra aleatoria de n = 35 economistas, se encuentre a no más de 1% de la media de la población de las estimaciones de todos los economistas?
 
b ¿Es necesariamente verdadero que la media de la población de las estimaciones de todos los economistas sea igual al porcentaje de ahorro en impuestos que en realidad se logrará?

6. El tiempo necesario para el mantenimiento periódico de un automóvil u otra máquina tiene por lo general una distribución de probabilidad en forma de campana. Debido a que se presentarán algunos alargamientos en los tiempos de servicio, la distribución tiende a estar sesgada a la derecha. Suponga que el tiempo necesario para dar servicio a un automóvil que ha recorrido 5000 millas tiene una media de 1.4 horas y desviación estándar de 0.7 horas. Suponga también que el departamento de servicio planea atender a 50 automóviles por jornada de 8 horas y que, para hacerlo, puede dedicar un tiempo promedio máximo de sólo 1.6 horas por automóvil. ¿Cuántos días tendrá que trabajar tiempo extra el departamento de servicio?

7. Se ha encontrado que las mediciones de resistencia al corte en soldaduras por puntos tienen una desviación estándar de 10 libras por pulgada cuadrada (psi). Si se han de medir 100 soldaduras de prueba, ¿cuál es la probabilidad aproximada de que la media muestral se encuentre a no más de 1 psi de la verdadera media poblacional?

Si la desviación estándar de mediciones de resistencia al corte en soldaduras por puntos es 10 psi, ¿cuántas soldaduras de prueba deben muestrearse si deseamos que la media muestral se encuentre a no más de 1 psi de la verdadera media con probabilidad aproximada de 0.99?

8. Los resistores que se han de usar en un circuito tienen un promedio de resistencia de 200 ohms y desviación estándar de 10 ohms. Suponga que 25 de estos resistores se seleccionan aleatoriamente para usarse en un circuito.
a ¿Cuál es la probabilidad de que la resistencia promedio para los 25 resistores esté entre 199 y 202 ohms?

b Encuentre la probabilidad de que la resistencia total no exceda de 5100 ohms.

9. Concentraciones de monóxido de carbono de cierta hora en muestras de aire de una gran ciudad promedian 12 ppm (partes por millón) con desviación estándar de 9 partes por millón.

a ¿Cree usted que las concentraciones de monóxido de carbono en las muestras de aire de esta ciudad están distribuidas normalmente? ¿Por qué sí o por qué no?

b Encuentre la probabilidad de que la concentración promedio en 100 muestras seleccionadas aleatoriamente exceda de 14 partes por millón.


## Distribución muestral de proporciones

1. Un medicamento para malestar estomacal tiene la advertencia de que algunos usuarios pueden presentar una reacción adversa a él, más aún, se piensa que alrededor del 3% de los usuarios tienen tal reacción. Si una muestra aleatoria de 150 personas con malestar estomacal usa el medicamento, encuentre la probabilidad de que la proporción de la muestra de los usuarios que realmente presentan una reacción adversa, exceda el 4%.

a. Resolverlo mediante distribución binomial Rta/0.1685

b. Resolverlo con la distribución muestral de proporciones

2. Se sabe que la verdadera proporción de los componentes defectuosos fabricadas por una firma es de 4%, y encuentre la probabilidad de que una muestra aleatoria de tamaño 60 tenga:

a. Menos del 3% de los componentes defectuosos. 0.2327

b. Más del 1% pero menos del 5% de partes defectuosas 0.3290




## Distribución muestral de la varianza

1. Los transistores fabricados por una compañía tienen una duración media de 2000 horas con una desviación típica de 60 horas. Si se selecciona una muestra de 10 transistores al azar de una población normal, ¿Cuál será la probabilidad que la desviación estándar muestral:

a) No supere las 50 horas?

b) Se encuentre entre 50 y 70 horas?

2. En una determinada prueba se supone que las calificaciones se distribuyen normalmente con un promedio de 80 puntos y desviación estándar de 10 puntos. Si mañana se debe aplicar una prueba de aptitud a 12 aspirantes:

a) ¿Cuál sería la probabilidad de que la desviación estándar de las calificaciones se dichos aspirantes sea mayor que 15 puntos?

b) ¿Cuál debería ser el mínimo valor de la desviación estándar de las calificaciones de dichos aspirantes con una probabilidad de 0.95?

3. Una máquina embotelladora puede regularse de tal manera que llene un promedio de  onzas por botella. Se ha observado que las onzas de contenido que vacía la máquina embotelladora tiene una distribución normal con  = 1 onzas.

Supóngase que se selecciona una muestra aleatoria de 10 botellas y se mide el contenido de cada botella. Usando las 10 observaciones hallar los números b1 y b2 tales que  $P(b_1≤ s^2≤b_2)=0.9$

(Sugerencia: Suponga que el 90% se encuentra en la parte central de la distribución a usar).

4. Viva air desea adquirir dispositivos electrónicos en el cual la varianza de las resistencias no debe exceder los 0.40 ohmios2. Para evitar la aceptación de remesas que no cumplen con esta especificación, el departamento de control de calidad toma una muestra aleatoria de 25 componentes de cada remesa y mide la resistencia de cada uno.

Si la varianza de la muestra es demasiado grande, el departamento rechaza el pedido. Se considera que una varianza muestral es demasiado grande si la probabilidad de que ocurra esto es superior a 0.02. Se acaba de seleccionar una muestra de una remesa y se obtiene s2 = 0.75. Debe aceptarse la remesa.


## Distribución muestral de la diferencia de medias

1. **DM para la diferencia de medias con Varianzas poblacionales desconocidas. Muestras grandes** 

1.1 Se estudia el efecto de un vertido tóxico en un río,comparando el índice de biodiversidad I.B-D. antes y después del vertido. Los I.B-D. siguen distribuciones Normales. Antes del vertido se habían realizado 35 pruebas y se obtuvo una media de 1.9 y una sd de 0.4. Después del vertido se realizan 40 pruebas y se obtiene una media de 1.7 y una sd de 0.7.

Obtener la probabilidad de que la media poblacional antes del vertido sea como máximo 0.5 unidades inferior a la media poblacional después del vertido.

$$P(\bar X \leq \bar Y+0.5) $$


1.2 En un estudio para comparar los pesos promedio de niños y niñas de sexto grado en una escuela primaria se usará una muestra aleatoria de 20 niños y otra de 25 niñas. Se sabe que tanto para niños como para niñas los pesos siguen una distribución normal. El promedio de los pesos de todos los niños de sexto grado de esa escuela es de 100 libras y su desviación estándar es de 14.142, mientras que el promedio de los pesos de todas las niñas del sexto grado de esa escuela es de 85 libras y su desviación estándar es de 12.247 libras. Si $X_1$  representa el promedio de los pesos de 20 niños y $X_2$es el promedio de los pesos de una muestra de 25 niñas.

Encuentre la probabilidad de que el promedio de los pesos de los 20 niños sea al menos 20 libras más grande que el de las 25 niñas.


1.3 Se prueba el rendimiento en km/L de 2 tipos de gasolina, encontrándose una desviación estándar de 1.23km/L para la primera gasolina y una desviación estándar de 1.37km/L para la segunda gasolina; se prueba la primera gasolina en 35 autos y la segunda en 42 autos.

a. ¿Cuál es la probabilidad de que la primera gasolina de un rendimiento promedio mayor de 0.45km/L que la segunda gasolina?

b.¿Cuál es la probabilidad de que la diferencia en rendimientos promedio se encuentre entre 0.65 y 0.83km/L a favor de la gasolina 1?.

1.4 Una muestra de tamaño 25 se toma de una población normal con media de 80 y desviación estándar 5; una segunda muestra de tamaño 36 se toma de una población normal con media 75 y desviación estándar de 3. Hallar la probabilidad de que la media de la muestra de tamaño 25 exceda a la media de la muestra de tamaño 36 en por lo menos 3.4 pero menos de 5.9.

1.5 Suponga que en el Ministerio de Trabajo se tiene registrado 20 mil trabajadores de construcción civil (C) y 15 mil trabajadores mineros (M).

El ingreso promedio mensual de los primeros es 900 soles con desviación estándar de 300 soles mientras que en el segundo, el ingreso promedio es de 1200 soles con un coeficiente de variación de 15%. El gobierno otorga un aumento general de 120 soles por costo de vida y 30 por movilidad.

Si luego del aumento se realiza un muestreo de 45 trabajadores de construcción civil y 64 mineros, ¿Cuál es la probabilidad de observar una diferencia de a lo más 350 soles entre las medias de ambas muestras?

2. **DM para la diferencia de medias con Varianzas poblacionales desconocidas pero iguales**

2.1 Según los registros históricos de ONER las bombillas fabricadas por la empresa PHIL, tiene una duración media de 6000 horas, mientras que las bombillas fabricadas por la empresa NATI tienen una duración de 8000 horas.

En una investigación de control de calidad de bombillas se encuentra que una muestra de 20 bombillas fabricadas por PHIL se encontró una desviación estándar de la vida útil de 1600 horas. Otra muestra aleatoria de 16 bombillas fabricada por la compañía NATI se encontró que la desviación estándar de la vida útil fue de 2600 horas.

¿Cuál es la probabilidad de que el promedio de vida útil de las bombillas fabricadas por NATI no difiera en más de 800 horas del promedio de vida útil de las bombillas fabricadas por PHIL?




3. **DM para la diferencia de medias con Varianzas poblacionales conocidas**




4.  **Varianzas poblacionales desconocidas y diferentes**


## Distribución muestral de la diferencia de proporciones


1. Se cree que el 30% de las mujeres y el 20% de los hombres aceptan cierto producto. Si se hace una encuesta a 200 hombres y 200 mujeres, elegidos al azar, ¿cuál es la probabilidad de que más mujeres que hombres acepten el producto?

2. Se cree que, de cada 100 baterías producidas por SOURCE, 10 son defectuosas y de cada 100 baterías fabricadas por FUENTE, 5 son defectuosas. Si se toma muestras al azar de 250 baterías tomadas de la producción de SOURCE y otra de 300 unidades de las fabricadas por FUENTE, ¿cuál es la probabilidad de observar una diferencia menor o igual a 0.02 en las proporciones muestrales de baterías defectuosas?

3. Los asesores de petro opinan que la proporción de ciudadanos a favor de su líder es de 45% en medellín y 50% en otras ciudades. Si se seleccionan muestras aleatorias de 400 y 250 en medellin y otras ciudades, respectivamente, ¿cuál es la probabilidad de que la proporción muestral de otras ciudades supere a la proporción muestral de medellín en más del 4%?.

4. Los hombres y mujeres adultos radicados en una ciudad grande del norte difieren en sus opiniones sobre la promulgación de la pena de muerte para personas culpables de asesinato. Se cree que el 12% de los hombres adultos están a favor de la pena de muerte, mientras que sólo 10% de las mujeres adultas lo están. Si se pregunta a dos muestras aleatorias de 100 hombres y 100 mujeres su opinión sobre la promulgación de la pena de muerte, determine la probabilidad de que el porcentaje de hombres a favor sea al menos 3% mayor que el de las mujeres.

## Ejercicios distribución muestral para la razón de varianzas

1. Estudios anteriores plantearon que la heterogeneidad en el nivel alcanzado por el PBI en América Latina, medida a través de la variabilidad de esta variable al interior de la región latinoamericana, siempre ha existido; esto es, de un año a otro puede esperarse que exista una similar variabilidad en el nivel del PBI registrado por los países latinos.

Partiéndose del PBI, expresado en millones de dólares, se obtuvieron los siguientes resultados: Que la desviación estándar del PBI registrado para el 2003 en una muestra de 16 países latinos fue de 67,803 mientras que para 2004 fue de 95,136.09.

Cuál es la probabilidad de que exista una mayor variabilidad en el año 2004 respecto a 203? Plantee los supuestos necesarios e interpreta los resultados.